const PictureData = [
  {
    id: "1",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz1.jpeg",
    Asli: 0,
  },
  {
    id: "2",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz2.jpg",
    Asli: 0,
  },
  {
    id: "3",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz3.jpeg",
    Asli: 1,
  },
  {
    id: "4",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz4.jpeg",
    Asli: 0,
  },
  {
    id: "5",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz5.jpeg",
    Asli: 0,
  },
  {
    id: "6",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz6.JPG",
    Asli: 0,
  },
  {
    id: "7",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz7.jpeg",
    Asli: 0,
  },
  {
    id: "8",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz8.JPG",
    Asli: 0,
  },
  {
    id: "9",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz9.jpeg",
    Asli: 1,
  },
  {
    id: "10",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz10.JPG",
    Asli: 0,
  },
  {
    id: "11",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz11.JPG",
    Asli: 0,
  },
  {
    id: "12",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz12.JPG",
    Asli: 0,
  },
  {
    id: "13",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz13.JPG",
    Asli: 1,
  },
  {
    id: "14",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz14.JPG",
    Asli: 0,
  },
  {
    id: "15",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz15.JPG",
    Asli: 0,
  },
  {
    id: "16",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz16.JPG",
    Asli: 0,
  },
  {
    id: "17",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz17.JPG",
    Asli: 1,
  },
  {
    id: "18",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz18.jpg",
    Asli: 0,
  },
  {
    id: "19",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz19.jpg",
    Asli: 0,
  },
  {
    id: "20",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz20.jpg",
    Asli: 0,
  },
  {
    id: "21",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz21.jpg",
    Asli: 0,
  },
  {
    id: "22",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz22.jpg",
    Asli: 1,
  },
  {
    id: "23",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz23.jpg",
    Asli: 0,
  },
  {
    id: "24",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz24.jpg",
    Asli: 0,
  },
  {
    id: "25",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz25.jpg",
    Asli: 1,
  },
  {
    id: "26",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz26.jpg",
    Asli: 0,
  },
  {
    id: "27",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz27.jpg",
    Asli: 0,
  },
  {
    id: "28",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz28.jpg",
    Asli: 0,
  },
  {
    id: "29",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz29.jpg",
    Asli: 0,
  },
  {
    id: "30",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz30.jpg",
    Asli: 0,
  },
  {
    id: "31",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz31.jpg",
    Asli: 0,
  },
  {
    id: "32",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz32.JPG",
    Asli: 0,
  },
  {
    id: "33",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz33.jpg",
    Asli: 0,
  },
  {
    id: "34",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz34.jpeg",
    Asli: 0,
  },
  {
    id: "35",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz35.jpg",
    Asli: 0,
  },
  {
    id: "36",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz36.jpg",
    Asli: 0,
  },
  {
    id: "37",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz37.jpg",
    Asli: 0,
  },
  {
    id: "38",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz38.jpg",
    Asli: 0,
  },
  {
    id: "39",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz39.jpeg",
    Asli: 0,
  },
  {
    id: "40",
    idProj: "3",
    name: "تصفیه خانه فاضلاب شهر تبریز",
    pic: "/images/projects/tabriz40.jpg",
    Asli: 0,
  },
  {
    id: "41",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran1.jpg",
    Asli: 0,
  },
  {
    id: "42",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran2.jpg",
    Asli: 1,
  },
  {
    id: "43",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran3.jpg",
    Asli: 0,
  },
  {
    id: "44",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran4.jpg",
    Asli: 0,
  },
  {
    id: "45",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran5.jpg",
    Asli: 0,
  },
  {
    id: "46",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran6.jpg",
    Asli: 0,
  },
  {
    id: "47",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran7.jpg",
    Asli: 0,
  },
  {
    id: "48",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran8.jpg",
    Asli: 0,
  },
  {
    id: "49",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran9.jpg",
    Asli: 0,
  },
  {
    id: "50",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran10.jpg",
    Asli: 0,
  },
  {
    id: "51",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran11.jpg",
    Asli: 0,
  },
  {
    id: "52",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran12.jpg",
    Asli: 0,
  },
  {
    id: "53",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran13.jpg",
    Asli: 1,
  },
  {
    id: "54",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran14.jpg",
    Asli: 0,
  },
  {
    id: "55",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran15.jpg",
    Asli: 0,
  },
  {
    id: "56",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran16.jpg",
    Asli: 0,
  },
  {
    id: "57",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran17.jpg",
    Asli: 0,
  },
  {
    id: "58",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran18.jpg",
    Asli: 0,
  },
  {
    id: "59",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran19.jpg",
    Asli: 0,
  },
  {
    id: "60",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran20.jpg",
    Asli: 0,
  },
  {
    id: "61",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran21.jpg",
    Asli: 0,
  },
  {
    id: "62",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran22.jpg",
    Asli: 0,
  },
  {
    id: "63",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran23.jpg",
    Asli: 0,
  },
  {
    id: "64",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran24.jpg",
    Asli: 0,
  },
  {
    id: "65",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran25.jpg",
    Asli: 0,
  },
  {
    id: "66",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran26.jpg",
    Asli: 0,
  },
  {
    id: "67",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran27.jpg",
    Asli: 0,
  },
  {
    id: "68",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran28.jpg",
    Asli: 0,
  },
  {
    id: "69",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran29.jpg",
    Asli: 0,
  },
  {
    id: "70",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran30.jpg",
    Asli: 0,
  },
  {
    id: "71",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran31.jpg",
    Asli: 0,
  },
  {
    id: "72",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran32.jpg",
    Asli: 0,
  },
  {
    id: "73",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran33.jpg",
    Asli: 0,
  },
  {
    id: "74",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran34.jpg",
    Asli: 0,
  },
  {
    id: "75",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran35.jpg",
    Asli: 0,
  },
  {
    id: "76",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran36.jpg",
    Asli: 0,
  },
  {
    id: "77",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran37.jpg",
    Asli: 0,
  },
  {
    id: "78",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran38.jpg",
    Asli: 0,
  },
  {
    id: "79",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran39.jpg",
    Asli: 0,
  },
  {
    id: "80",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran40.jpg",
    Asli: 0,
  },
  {
    id: "81",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran41.jpg",
    Asli: 0,
  },
  {
    id: "82",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran42.jpg",
    Asli: 0,
  },
  {
    id: "83",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran43.jpg",
    Asli: 0,
  },
  {
    id: "84",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran44.jpg",
    Asli: 1,
  },
  {
    id: "85",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran45.jpg",
    Asli: 0,
  },
  {
    id: "86",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran46.jpg",
    Asli: 0,
  },
  {
    id: "87",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran47.jpg",
    Asli: 0,
  },
  {
    id: "88",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran48.jpg",
    Asli: 0,
  },
  {
    id: "89",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran49.jpg",
    Asli: 0,
  },
  {
    id: "90",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran50.jpg",
    Asli: 0,
  },
  {
    id: "91",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran51.jpg",
    Asli: 0,
  },
  {
    id: "92",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran52.jpg",
    Asli: 1,
  },
  {
    id: "93",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran53.jpg",
    Asli: 0,
  },
  {
    id: "94",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran54.jpg",
    Asli: 0,
  },
  {
    id: "95",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran55.jpg",
    Asli: 1,
  },
  {
    id: "96",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran56.jpg",
    Asli: 0,
  },
  {
    id: "97",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    pic: "/images/projects/tehran57.jpg",
    Asli: 0,
  },
  {
    id: "98",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan1.jpeg",
    Asli: 0,
  },
  {
    id: "99",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan2.jpeg",
    Asli: 0,
  },
  {
    id: "100",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan3.jpeg",
    Asli: 0,
  },
  {
    id: "101",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan4.jpg",
    Asli: 0,
  },
  {
    id: "102",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan5.jpg",
    Asli: 0,
  },
  {
    id: "103",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan6.jpg",
    Asli: 0,
  },
  {
    id: "104",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan7.jpg",
    Asli: 0,
  },
  {
    id: "105",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan8.jpg",
    Asli: 0,
  },
  {
    id: "106",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan9.jpg",
    Asli: 0,
  },
  {
    id: "107",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan10.jpg",
    Asli: 0,
  },
  {
    id: "108",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan11.jpg",
    Asli: 1,
  },
  {
    id: "109",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan12.jpg",
    Asli: 0,
  },
  {
    id: "110",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan13.jpg",
    Asli: 0,
  },
  {
    id: "111",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan14.jpg",
    Asli: 0,
  },
  {
    id: "112",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan15.jpg",
    Asli: 0,
  },
  {
    id: "113",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan16.jpg",
    Asli: 0,
  },
  {
    id: "114",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan17.jpg",
    Asli: 0,
  },
  {
    id: "115",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan18.jpg",
    Asli: 0,
  },
  {
    id: "116",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan19.jpg",
    Asli: 0,
  },
  {
    id: "117",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan20.jpg",
    Asli: 0,
  },
  {
    id: "118",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan21.jpg",
    Asli: 1,
  },
  {
    id: "119",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan22.jpg",
    Asli: 0,
  },
  {
    id: "120",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan23.jpg",
    Asli: 0,
  },
  {
    id: "121",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan24.jpg",
    Asli: 0,
  },
  {
    id: "122",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan25.jpg",
    Asli: 0,
  },
  {
    id: "123",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan26.jpg",
    Asli: 0,
  },
  {
    id: "124",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan27.jpg",
    Asli: 0,
  },
  {
    id: "125",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan28.jpg",
    Asli: 1,
  },
  {
    id: "126",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan29.jpg",
    Asli: 0,
  },
  {
    id: "127",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan30.jpg",
    Asli: 0,
  },
  {
    id: "128",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan31.jpg",
    Asli: 0,
  },
  {
    id: "129",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan32.jpg",
    Asli: 0,
  },
  {
    id: "130",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan33.jpg",
    Asli: 0,
  },
  {
    id: "131",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan34.jpg",
    Asli: 0,
  },
  {
    id: "132",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan35.jpg",
    Asli: 1,
  },
  {
    id: "133",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan36.jpg",
    Asli: 1,
  },
  {
    id: "134",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan37.jpg",
    Asli: 0,
  },
  {
    id: "135",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan38.jpg",
    Asli: 1,
  },
  {
    id: "136",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan39.jpg",
    Asli: 0,
  },
  {
    id: "137",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan40.jpg",
    Asli: 0,
  },
  {
    id: "138",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan41.jpg",
    Asli: 0,
  },
  {
    id: "139",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan42.jpg",
    Asli: 0,
  },
  {
    id: "140",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan43.jpg",
    Asli: 0,
  },
  {
    id: "141",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان",
    pic: "/images/projects/vavan44.jpg",
    Asli: 1,
  },
  {
    id: "142",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan1.JPG",
    Asli: 0,
  },
  {
    id: "143",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan2.JPG",
    Asli: 1,
  },
  {
    id: "144",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan3.JPG",
    Asli: 0,
  },
  {
    id: "145",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan4.JPG",
    Asli: 0,
  },
  {
    id: "146",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan5.JPG",
    Asli: 0,
  },
  {
    id: "147",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan6.JPG",
    Asli: 1,
  },
  {
    id: "148",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan7.JPG",
    Asli: 0,
  },
  {
    id: "149",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan8.JPG",
    Asli: 0,
  },
  {
    id: "150",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan9.JPG",
    Asli: 0,
  },
  {
    id: "151",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan10.JPG",
    Asli: 0,
  },
  {
    id: "152",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    pic: "/images/projects/roodan11.JPG",
    Asli: 0,
  },
  {
    id: "153",
    idProj: "8",
    name: " تصفیه خانه فاضلاب شهر محمود آباد",
    pic: "/images/projects/mahmoodabad1.JPG",
    Asli: 0,
  },
  {
    id: "154",
    idProj: "8",
    name: " تصفیه خانه فاضلاب شهر محمود آباد",
    pic: "/images/projects/mahmoodabad2.JPG",
    Asli: 1,
  },
  {
    id: "155",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT1.jpeg",
    Asli: 0,
  },
  {
    id: "156",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT2.jpg",
    Asli: 1,
  },
  {
    id: "157",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT3.jpg",
    Asli: 0,
  },
  {
    id: "158",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT4.jpeg",
    Asli: 0,
  },
  {
    id: "159",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT5.jpeg",
    Asli: 1,
  },
  {
    id: "160",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT6.jpg",
    Asli: 0,
  },
  {
    id: "161",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT7.jpeg",
    Asli: 0,
  },
  {
    id: "162",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT8.jpg",
    Asli: 0,
  },
  {
    id: "163",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT9.jpg",
    Asli: 0,
  },
  {
    id: "164",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT10.jpg",
    Asli: 0,
  },
  {
    id: "165",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT11.jpg",
    Asli: 0,
  },
  {
    id: "166",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT12.jpg",
    Asli: 0,
  },
  {
    id: "167",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT13.jpg",
    Asli: 1,
  },
  {
    id: "168",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT14.jpg",
    Asli: 0,
  },
  {
    id: "169",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT15.jpg",
    Asli: 0,
  },
  {
    id: "170",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT16.jpg",
    Asli: 0,
  },
  {
    id: "171",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT17.jpg",
    Asli: 0,
  },
  {
    id: "172",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT18.jpg",
    Asli: 0,
  },
  {
    id: "173",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT19.jpg",
    Asli: 0,
  },
  {
    id: "174",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    pic: "/images/projects/sariWT20.jpg",
    Asli: 0,
  },
  {
    id: "175",
    idProj: "1",
    name: " تصفیه خانه آب شهر بم",
    pic: "/images/projects/bam1.jpg",
    Asli: 1,
  },
  {
    id: "176",
    idProj: "1",
    name: " تصفیه خانه آب شهر بم",
    pic: "/images/projects/bam2.jpg",
    Asli: 0,
  },
  {
    id: "177",
    idProj: "1",
    name: " تصفیه خانه آب شهر بم",
    pic: "/images/projects/bam3.jpg",
    Asli: 0,
  },
  {
    id: "178",
    idProj: "1",
    name: " تصفیه خانه آب شهر بم",
    pic: "/images/projects/bam4.jpg",
    Asli: 0,
  },
  {
    id: "179",
    idProj: "7",
    name: " تصفیه خانه آب شهر خلخال",
    pic: "/images/projects/khalkhal1.jpeg",
    Asli: 0,
  },
  {
    id: "180",
    idProj: "7",
    name: " تصفیه خانه آب شهر خلخال",
    pic: "/images/projects/khalkhal2.jpeg",
    Asli: 1,
  },
  {
    id: "181",
    idProj: "7",
    name: " تصفیه خانه آب شهر خلخال",
    pic: "/images/projects/khalkhal3.jpeg",
    Asli: 0,
  },
  {
    id: "182",
    idProj: "7",
    name: " تصفیه خانه آب شهر خلخال",
    pic: "/images/projects/khalkhal4.jpeg",
    Asli: 0,
  },
  {
    id: "183",
    idProj: "7",
    name: " تصفیه خانه آب شهر خلخال",
    pic: "/images/projects/khalkhal5.jpeg",
    Asli: 0,
  },
  {
    id: "184",
    idProj: "7",
    name: " تصفیه خانه آب شهر خلخال",
    pic: "/images/projects/khalkhal6.jpeg",
    Asli: 0,
  },
  {
    id: "185",
    idProj: "7",
    name: " تصفیه خانه آب شهر خلخال",
    pic: "/images/projects/khalkhal7.jpeg",
    Asli: 0,
  },
  {
    id: "186",
    idProj: "7",
    name: " تصفیه خانه آب شهر خلخال",
    pic: "/images/projects/khalkhal8.jpeg",
    Asli: 0,
  },
  {
    id: "187",
    idProj: "7",
    name: " تصفیه خانه آب شهر خلخال",
    pic: "/images/projects/khalkhal9.jpeg",
    Asli: 0,
  },
  {
    id: "188",
    idProj: "7",
    name: " تصفیه خانه آب شهر خلخال",
    pic: "/images/projects/khalkhal10.jpeg",
    Asli: 0,
  },
  {
    id: "189",
    idProj: "7",
    name: " تصفیه خانه آب شهر خلخال",
    pic: "/images/projects/khalkhal11.jpeg",
    Asli: 0,
  },
  {
    id: "190",
    idProj: "11",
    name: " تصفیه خانه فاضلاب صنایع لاستیک تایر کرد",
    pic: "/images/projects/tayerKord1.jpg",
    Asli: 1,
  },
  {
    id: "191",
    idProj: "11",
    name: " تصفیه خانه فاضلاب صنایع لاستیک تایر کرد",
    pic: "/images/projects/tayerKord2.jpg",
    Asli: 0,
  },
  {
    id: "192",
    idProj: "11",
    name: " تصفیه خانه فاضلاب صنایع لاستیک تایر کرد",
    pic: "/images/projects/tayerKord3.jpg",
    Asli: 3,
  },
  {
    id: "193",
    idProj: "12",
    name: " تصفیه خانه فاضلاب شهرک صنعتی شهید سلیمی ",
    pic: "/images/projects/shahidS1.JPG",
    Asli: 1,
  },
  {
    id: "194",
    idProj: "12",
    name: " تصفیه خانه فاضلاب شهرک صنعتی شهید سلیمی ",
    pic: "/images/projects/shahidS2.JPG",
    Asli: 0,
  },
  {
    id: "195",
    idProj: "13",
    name: " تصفیه خانه فاضلاب شهرک صنعتی شمس آباد ",
    pic: "/images/projects/shamsabad1.jpg",
    Asli: 0,
  },
  {
    id: "196",
    idProj: "13",
    name: " تصفیه خانه فاضلاب شهرک صنعتی شمس آباد ",
    pic: "/images/projects/shamsabad2.jpg",
    Asli: 1,
  },
  {
    id: "197",
    idProj: "14",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan1.JPG",
    Asli: 0,
  },
  {
    id: "198",
    idProj: "14",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan2.JPG",
    Asli: 0,
  },
  {
    id: "199",
    idProj: "14",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan3.JPG",
    Asli: 0,
  },
  {
    id: "200",
    idProj: "14",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan4.JPG",
    Asli: 0,
  },
  {
    id: "201",
    idProj: "14",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan5.JPG",
    Asli: 1,
  },
  {
    id: "202",
    idProj: "14",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan6.JPG",
    Asli: 0,
  },
  {
    id: "203",
    idProj: "14",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan7.JPG",
    Asli: 0,
  },
  {
    id: "204",
    idProj: "14",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan8.JPG",
    Asli: 0,
  },
  {
    id: "205",
    idProj: "14",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan9.JPG",
    Asli: 0,
  },
  {
    id: "206",
    idProj: "14",
    name: " تصفیه خانه فاضلاب بهارستان ",
    pic: "/images/projects/baharestan10.JPG",
    Asli: 0,
  },
  {
    id: "207",
    idProj: "15",
    name: " تصفیه خانه فاضلاب شهرک صنعتی بهارستان ",
    pic: "/images/projects/baharestanS1.jpg",
    Asli: 0,
  },
  {
    id: "208",
    idProj: "15",
    name: " تصفیه خانه فاضلاب شهرک صنعتی بهارستان ",
    pic: "/images/projects/baharestanS2.jpg",
    Asli: 1,
  },
  {
    id: "209",
    idProj: "16",
    name: " تصفیه خانه اضطراری آب عباس آباد همدان ",
    pic: "/images/projects/hamedan1.jpg",
    Asli: 0,
  },
  {
    id: "210",
    idProj: "16",
    name: " تصفیه خانه اضطراری آب عباس آباد همدان ",
    pic: "/images/projects/hamedan2.jpg",
    Asli: 1,
  },
  {
    id: "211",
    idProj: "16",
    name: " تصفیه خانه اضطراری آب عباس آباد همدان ",
    pic: "/images/projects/hamedan3.jpg",
    Asli: 0,
  },
  {
    id: "212",
    idProj: "17",
    name: " تصفیه خانه فاضلاب شهر اردبیل ",
    pic: "/images/projects/ardebil1.jpg",
    Asli: 0,
  },
  {
    id: "213",
    idProj: "17",
    name: " تصفیه خانه فاضلاب شهر اردبیل ",
    pic: "/images/projects/ardebil2.jpg",
    Asli: 1,
  },
  {
    id: "214",
    idProj: "17",
    name: " تصفیه خانه فاضلاب شهر اردبیل ",
    pic: "/images/projects/ardebil3.jpg",
    Asli: 0,
  },
  {
    id: "215",
    idProj: "17",
    name: " تصفیه خانه فاضلاب شهر اردبیل ",
    pic: "/images/projects/ardebil4.JPG",
    Asli: 1,
  },
  {
    id: "216",
    idProj: "17",
    name: " تصفیه خانه فاضلاب شهر اردبیل ",
    pic: "/images/projects/ardebil5.JPG",
    Asli: 0,
  },
  {
    id: "217",
    idProj: "18",
    name: " تصفیه خانه آب شهر تکاب ",
    pic: "/images/projects/takab1.JPG",
    Asli: 1,
  },
  {
    id: "218",
    idProj: "18",
    name: " تصفیه خانه آب شهر تکاب ",
    pic: "/images/projects/takab2.JPG",
    Asli: 1,
  },
  {
    id: "219",
    idProj: "18",
    name: " تصفیه خانه آب شهر تکاب ",
    pic: "/images/projects/takab3.JPG",
    Asli: 0,
  },
  {
    id: "220",
    idProj: "18",
    name: " تصفیه خانه آب شهر تکاب ",
    pic: "/images/projects/takab4.JPG",
    Asli: 0,
  },
  {
    id: "221",
    idProj: "18",
    name: " تصفیه خانه آب شهر تکاب ",
    pic: "/images/projects/takab5.JPG",
    Asli: 0,
  },
  {
    id: "222",
    idProj: "18",
    name: " تصفیه خانه آب شهر تکاب ",
    pic: "/images/projects/takab6.JPG",
    Asli: 1,
  },
  {
    id: "223",
    idProj: "18",
    name: " تصفیه خانه آب شهر تکاب ",
    pic: "/images/projects/takab7.jpg",
    Asli: 0,
  },
  {
    id: "224",
    idProj: "19",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad1.jpg",
    Asli: 0,
  },
  {
    id: "225",
    idProj: "19",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad2.jpg",
    Asli: 0,
  },
  {
    id: "226",
    idProj: "19",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad3.JPG",
    Asli: 1,
  },
  {
    id: "227",
    idProj: "19",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad4.JPG",
    Asli: 0,
  },
  {
    id: "228",
    idProj: "19",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad5.JPG",
    Asli: 1,
  },
  {
    id: "229",
    idProj: "19",
    name: " تصفیه خانه فاضلاب شهر مهاباد ",
    pic: "/images/projects/mahabad6.jpg",
    Asli: 0,
  },
  {
    id: "230",
    idProj: "20",
    name: " تصفیه خانه فاضلاب شهر بندر گز ",
    pic: "/images/projects/bandarGaz1.jpg",
    Asli: 1,
  },
  {
    id: "231",
    idProj: "20",
    name: " تصفیه خانه فاضلاب شهر بندر گز ",
    pic: "/images/projects/bandarGaz2.JPG",
    Asli: 0,
  },
  {
    id: "232",
    idProj: "20",
    name: " تصفیه خانه فاضلاب شهر بندر گز ",
    pic: "/images/projects/bandarGaz3.JPG",
    Asli: 0,
  },
  {
    id: "233",
    idProj: "20",
    name: " تصفیه خانه فاضلاب شهر بندر گز ",
    pic: "/images/projects/bandarGaz4.JPG",
    Asli: 0,
  },
  {
    id: "234",
    idProj: "21",
    name: " تصفیه خانه فاضلاب دزفول ",
    pic: "/images/projects/dezfool1.jpg",
    Asli: 1,
  },
  {
    id: "235",
    idProj: "21",
    name: " تصفیه خانه فاضلاب دزفول ",
    pic: "/images/projects/dezfool2.jpg",
    Asli: 0,
  },
  {
    id: "236",
    idProj: "22",
    name: " تصفیه خانه فاضلاب سمنان ",
    pic: "/images/projects/saman1.jpg",
    Asli: 0,
  },
  {
    id: "237",
    idProj: "22",
    name: " تصفیه خانه فاضلاب سمنان ",
    pic: "/images/projects/saman2.jpg",
    Asli: 1,
  },
  {
    id: "238",
    idProj: "22",
    name: " تصفیه خانه فاضلاب سمنان ",
    pic: "/images/projects/saman3.jpg",
    Asli: 0,
  },
  {
    id: "239",
    idProj: "23",
    name: " تلمبه خانه فاضلاب ساری ",
    pic: "/images/projects/sariP1.JPG",
    Asli: 1,
  },
  {
    id: "240",
    idProj: "23",
    name: " تلمبه خانه فاضلاب ساری ",
    pic: "/images/projects/sariP2.JPG",
    Asli: 0,
  },
  {
    id: "241",
    idProj: "23",
    name: " تلمبه خانه فاضلاب ساری ",
    pic: "/images/projects/sariP3.JPG",
    Asli: 0,
  },
  {
    id: "242",
    idProj: "23",
    name: " تلمبه خانه فاضلاب ساری ",
    pic: "/images/projects/sariP4.JPG",
    Asli: 0,
  },
  {
    id: "243",
    idProj: "23",
    name: " تلمبه خانه فاضلاب ساری ",
    pic: "/images/projects/sariP5.JPG",
    Asli: 0,
  },
  {
    id: "244",
    idProj: "23",
    name: " تلمبه خانه فاضلاب ساری ",
    pic: "/images/projects/sariP6.JPG",
    Asli: 1,
  },
  {
    id: "245",
    idProj: "24",
    name: " تصفیه خانه فاضلاب شهر کردکوی",
    pic: "/images/projects/kordkooy1.JPG",
    Asli: 0,
  },
  {
    id: "246",
    idProj: "24",
    name: " تصفیه خانه فاضلاب شهر کردکوی",
    pic: "/images/projects/kordkooy2.JPG",
    Asli: 0,
  },
  {
    id: "247",
    idProj: "24",
    name: " تصفیه خانه فاضلاب شهر کردکوی",
    pic: "/images/projects/kordkooy3.JPG",
    Asli: 0,
  },
  {
    id: "248",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin1.JPG",
    Asli: 1,
  },
  {
    id: "249",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin2.JPG",
    Asli: 0,
  },
  {
    id: "250",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin3.JPG",
    Asli: 0,
  },
  {
    id: "251",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin4.jpg",
    Asli: 0,
  },
  {
    id: "252",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin5.jpg",
    Asli: 0,
  },
  {
    id: "253",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin6.jpg",
    Asli: 0,
  },
  {
    id: "254",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin7.jpg",
    Asli: 0,
  },
  {
    id: "255",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin8.JPG",
    Asli: 0,
  },
  {
    id: "256",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin9.JPG",
    Asli: 0,
  },
  {
    id: "257",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin10.JPG",
    Asli: 0,
  },
  {
    id: "258",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin11.JPG",
    Asli: 0,
  },
  {
    id: "259",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin12.JPG",
    Asli: 0,
  },
  {
    id: "260",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin13.JPG",
    Asli: 0,
  },
  {
    id: "261",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin14.JPG",
    Asli: 0,
  },
  {
    id: "262",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin15.JPG",
    Asli: 0,
  },
  {
    id: "263",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin16.JPG",
    Asli: 0,
  },
  {
    id: "264",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin17.JPG",
    Asli: 0,
  },
  {
    id: "265",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin18.JPG",
    Asli: 0,
  },
  {
    id: "266",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin19.JPG",
    Asli: 0,
  },
  {
    id: "267",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin20.JPG",
    Asli: 1,
  },
  {
    id: "268",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin21.JPG",
    Asli: 0,
  },
  {
    id: "269",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin22.JPG",
    Asli: 1,
  },
  {
    id: "270",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin23.JPG",
    Asli: 0,
  },
  {
    id: "271",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin24.JPG",
    Asli: 0,
  },
  {
    id: "272",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    pic: "/images/projects/mobin25.JPG",
    Asli: 1,
  },
  {
    id: "273",
    idProj: "26",
    name: " تصفیه خانه فاضلاب تویسرکان",
    pic: "/images/projects/tooyserkan1.jpg",
    Asli: 0,
  },
  {
    id: "274",
    idProj: "26",
    name: " تصفیه خانه فاضلاب تویسرکان",
    pic: "/images/projects/tooyserkan2.jpg",
    Asli: 1,
  },
  {
    id: "275",
    idProj: "26",
    name: " تصفیه خانه فاضلاب تویسرکان",
    pic: "/images/projects/tooyserkan3.jpg",
    Asli: 0,
  },
  {
    id: "276",
    idProj: "26",
    name: " تصفیه خانه فاضلاب تویسرکان",
    pic: "/images/projects/tooyserkan4.jpg",
    Asli: 0,
  },
  {
    id: "277",
    idProj: "26",
    name: " تصفیه خانه فاضلاب تویسرکان",
    pic: "/images/projects/tooyserkan5.jpg",
    Asli: 0,
  },
  {
    id: "278",
    idProj: "26",
    name: " تصفیه خانه فاضلاب تویسرکان",
    pic: "/images/projects/tooyserkan6.jpg",
    Asli: 0,
  },
  {
    id: "279",
    idProj: "26",
    name: " تصفیه خانه فاضلاب تویسرکان",
    pic: "/images/projects/tooyserkan7.jpg",
    Asli: 0,
  },
  {
    id: "280",
    idProj: "26",
    name: " تصفیه خانه فاضلاب تویسرکان",
    pic: "/images/projects/tooyserkan8.jpg",
    Asli: 0,
  },
  {
    id: "281",
    idProj: "26",
    name: " تصفیه خانه فاضلاب تویسرکان",
    pic: "/images/projects/tooyserkan9.jpg",
    Asli: 1,
  },
  {
    id: "282",
    idProj: "28",
    name: " تصفیه خانه فاضلاب سامان",
    pic: "/images/projects/saman1.jpg",
    Asli: 0,
  },
  {
    id: "283",
    idProj: "28",
    name: " تصفیه خانه فاضلاب سامان",
    pic: "/images/projects/saman2.jpg",
    Asli: 0,
  },
  {
    id: "284",
    idProj: "28",
    name: " تصفیه خانه فاضلاب سامان",
    pic: "/images/projects/saman3.jpg",
    Asli: 0,
  },
  {
    id: "285",
    idProj: "29",
    name: " تصفیه خانه فاضلاب شهر پاوه",
    pic: "/images/projects/paveh1.jpg",
    Asli: 1,
  },
  {
    id: "286",
    idProj: "29",
    name: " تصفیه خانه فاضلاب شهر پاوه",
    pic: "/images/projects/paveh2.jpg",
    Asli: 0,
  },
  {
    id: "287",
    idProj: "29",
    name: " تصفیه خانه فاضلاب شهر پاوه",
    pic: "/images/projects/paveh3.JPG",
    Asli: 0,
  },
  {
    id: "288",
    idProj: "29",
    name: " تصفیه خانه فاضلاب شهر پاوه",
    pic: "/images/projects/paveh4.JPG",
    Asli: 0,
  },
  {
    id: "289",
    idProj: "29",
    name: " تصفیه خانه فاضلاب شهر پاوه",
    pic: "/images/projects/paveh5.jpg",
    Asli: 0,
  },
  {
    id: "290",
    idProj: "30",
    name: " تصفیه خانه فاضلاب عجب شیر ",
    pic: "/images/projects/ajabshir1.jpg",
    Asli: 1,
  },
  {
    id: "291",
    idProj: "30",
    name: " تصفیه خانه فاضلاب عجب شیر ",
    pic: "/images/projects/ajabshir2.jpg",
    Asli: 0,
  },
  {
    id: "292",
    idProj: "30",
    name: " تصفیه خانه فاضلاب عجب شیر ",
    pic: "/images/projects/ajabshir3.jpg",
    Asli: 0,
  },
  {
    id: "293",
    idProj: "31",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer1.jpg",
    Asli: 0,
  },
  {
    id: "294",
    idProj: "31",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer2.JPG",
    Asli: 0,
  },
  {
    id: "295",
    idProj: "31",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer3.JPG",
    Asli: 1,
  },
  {
    id: "296",
    idProj: "31",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer4.JPG",
    Asli: 0,
  },
  {
    id: "297",
    idProj: "31",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer5.JPG",
    Asli: 0,
  },
  {
    id: "298",
    idProj: "31",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer6.JPG",
    Asli: 0,
  },
  {
    id: "299",
    idProj: "31",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer7.JPG",
    Asli: 1,
  },
  {
    id: "300",
    idProj: "31",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer8.jpg",
    Asli: 0,
  },
  {
    id: "301",
    idProj: "31",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer9.jpg",
    Asli: 0,
  },
  {
    id: "302",
    idProj: "31",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer10.jpg",
    Asli: 0,
  },
  {
    id: "303",
    idProj: "31",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer11.jpg",
    Asli: 0,
  },
  {
    id: "304",
    idProj: "31",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer12.jpg",
    Asli: 0,
  },
  {
    id: "305",
    idProj: "31",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer13.jpg",
    Asli: 0,
  },
  {
    id: "306",
    idProj: "31",
    name: " تصفیه خانه فاضلاب ملایر ",
    pic: "/images/projects/malayer14.jpg",
    Asli: 0,
  },
  {
    id: "307",
    idProj: "10",
    name: " آبرسانی به صنایع  مستقر در ایجرود از سد گلابر شهرستان ایجرود ",
    pic: "/images/projects/Ijrood1.png",
    Asli: 1,
  },
  {
    id: "308",
    idProj: "10",
    name: " آبرسانی به صنایع  مستقر در ایجرود از سد گلابر شهرستان ایجرود ",
    pic: "/images/projects/Ijrood2.png",
    Asli: 0,
  },
  {
    id: "309",
    idProj: "10",
    name: " آبرسانی به صنایع  مستقر در ایجرود از سد گلابر شهرستان ایجرود ",
    pic: "/images/projects/Ijrood3.png",
    Asli: 0,
  },
  {
    id: "310",
    idProj: "10",
    name: " آبرسانی به صنایع  مستقر در ایجرود از سد گلابر شهرستان ایجرود ",
    pic: "/images/projects/Ijrood4.png",
    Asli: 0,
  },
  {
    id: "311",
    idProj: "27",
    name: " تلمبه خانه برداشت آب از سد جگین ",
    pic: "/images/projects/jegin1.JPG",
    Asli: 0,
  },
  {
    id: "312",
    idProj: "27",
    name: " تلمبه خانه برداشت آب از سد جگین",
    pic: "/images/projects/jegin2.JPG",
    Asli: 1,
  },
  {
    id: "313",
    idProj: "2",
    name: " تصفیه خانه آب شهر میانه",
    pic: "/images/projects/Mianeh1.png",
    Asli: 1,
  },
  {
    id: "314",
    idProj: "2",
    name: " تصفیه خانه آب شهر میانه",
    pic: "/images/projects/Mianeh2.png",
    Asli: 0,
  },
  {
    id: "315",
    idProj: "2",
    name: " تصفیه خانه آب شهر میانه",
    pic: "/images/projects/Mianeh3.jpeg",
    Asli: 0,
  },
];
export { PictureData };
