const PictureData = [
  { id: "1", idProj: "21",name:" تصفیه خانه فاضلاب شهر اردبیل", pic: "/images/projects/Ardebil1.png" },
  { id: "2", idProj: "21",name:" تصفیه خانه فاضلاب شهر اردبیل", pic: "/images/projects/Ardebil2.png" },
  { id: "3", idProj: "21",name:" تصفیه خانه فاضلاب شهر اردبیل", pic: "/images/projects/Ardebil3.png" },
  { id: "4", idProj: "10",name:" تصفیه خانه فاضلاب بهارستان", pic: "/images/projects/Baharestan1.jpg" },
  { id: "5", idProj: "10",name:" تصفیه خانه فاضلاب بهارستان", pic: "/images/projects/Baharestan2.jpg" },
  { id: "6", idProj: "23",name:" تصفیه خانه فاضلاب شهرک صنعتی بهارستان", pic: "/images/projects/Baharestan21.jpg" },
  { id: "7", idProj: "23",name:" تصفیه خانه فاضلاب شهرک صنعتی بهارستان", pic: "/images/projects/Baharestan22.jpg" },
  { id: "8", idProj: "10",name:" تصفیه خانه فاضلاب بهارستان", pic: "/images/projects/Baharestan3.jpg" },
  { id: "9", idPr9oj: "9",name:" تصفیه خانه آب شهر بم", pic: "/images/projects/Bam1.png" },
  { id: "10", idProj: "9",name:" تصفیه خانه آب شهر بم", pic: "/images/projects/Bam2.jpg" },
  { id: "11", idProj: "16",name:" تصفیه خانه فاضلاب دزفول", pic: "/images/projects/Dezfool1.png" },
  { id: "12", idProj: "16",name:" تصفیه خانه فاضلاب دزفول", pic: "/images/projects/Dezfool2.png" },
  { id: "13", idProj: "16",name:" تصفیه خانه فاضلاب دزفول", pic: "/images/projects/Dezfool3.png" },
  
  { id: "15", idProj: "18",name:" تصفیه خانه فاضلاب شهر بندر گز", pic: "/images/projects/Gaz1.jpg" },
  { id: "16", idProj: "18",name:" تصفیه خانه فاضلاب شهر بندر گز", pic: "/images/projects/Gaz2.jpg" },
  { id: "17", idProj: "18",name:" تصفیه خانه فاضلاب شهر بندر گز", pic: "/images/projects/Gaz3.jpg" },
  { id: "18", idProj: "27",name:"آبرسانی به صنایع  مستقر در ایجرود از سد گلابر شهرستان ایجرود", pic: "/images/projects/Golabar1.png" },
  { id: "19", idProj: "27",name:"آبرسانی به صنایع  مستقر در ایجرود از سد گلابر شهرستان ایجرود", pic: "/images/projects/Golabar2.jpg" },
  { id: "20", idProj: "22",name:" تصفیه خانه اضطراری آب عباس آباد همدان", pic: "/images/projects/Hamedan1.jpg" },
  { id: "21", idProj: "22",name:" تصفیه خانه اضطراری آب عباس آباد همدان", pic: "/images/projects/Hamedan2.jpg" },
  { id: "22", idProj: "7",name:" تصفیه خانه آب شهر خلخال", pic: "/images/projects/KhalKhal1.jpg" },
  { id: "23", idProj: "7",name:" تصفیه خانه آب شهر خلخال", pic: "/images/projects/KhalKhal2.jpg" },
  { id: "24", idProj: "7",name:" تصفیه خانه آب شهر خلخال", pic: "/images/projects/KhalKhal3.jpg" },
  { id: "25", idProj: "26",name:" تصفیه خانه فاضلاب صنایع لاستیک تایر کرد", pic: "/images/projects/Kord1.png" },
  { id: "26", idProj: "26",name:" تصفیه خانه فاضلاب صنایع لاستیک تایر کرد", pic: "/images/projects/Kord2.png" },
  { id: "27", idProj: "13",name:" تصفیه خانه فاضلاب شهر کردکوی", pic: "/images/projects/Kordkooy1.jpg" },
  { id: "28", idProj: "13",name:" تصفیه خانه فاضلاب شهر کردکوی", pic: "/images/projects/Kordkooy2.jpg" },
  { id: "29", idProj: "17",name:" تصفیه خانه فاضلاب شهر کردکوی", pic: "/images/projects/Kordkooy21.jpg" },
  { id: "30", idProj: "17",name:" تصفیه خانه فاضلاب شهر کردکوی", pic: "/images/projects/Kordkooy22.jpg" },
  { id: "31", idProj: "17",name:" تصفیه خانه فاضلاب شهر کردکوی", pic: "/images/projects/Kordkooy23.jpg" },
  { id: "32", idProj: "13",name:" تصفیه خانه فاضلاب شهر کردکوی", pic: "/images/projects/Kordkooy3.jpg" },
  { id: "33", idProj: "19",name:" تصفیه خانه فاضلاب شهر مهاباد", pic: "/images/projects/Mahabad1.jpg" },
  { id: "34", idProj: "19",name:" تصفیه خانه فاضلاب شهر مهاباد", pic: "/images/projects/Mahabad2.jpg" },
  { id: "35", idProj: "19",name:" تصفیه خانه فاضلاب شهر مهاباد", pic: "/images/projects/Mahabad3.jpg" },
  { id: "36", idProj: "5",name:" تصفیه خانه فاضلاب شهر محمود آباد", pic: "/images/projects/Mahmood1.jpg" },
  { id: "37", idProj: "5",name:" تصفیه خانه فاضلاب شهر محمود آباد", pic: "/images/projects/Mahmood2.jpg" },
  { id: "38", idProj: "8",name:" تصفیه خانه آب شهر میانه", pic: "/images/projects/Mianeh1.jpg" },
  { id: "39", idProj: "8",name:" تصفیه خانه آب شهر میانه", pic: "/images/projects/Mianeh2.jpg" },
  { id: "40", idProj: "12",name:" تصفیه خانه فاضلاب مجتمع پتروشیمی مبین", pic: "/images/projects/Mobin1.jpg" },
  { id: "41", idProj: "12",name:" تصفیه خانه فاضلاب مجتمع پتروشیمی مبین", pic: "/images/projects/Mobin2.jpg" },
  { id: "42", idProj: "4",name:" تصفیه خانه فاضلاب شهر رودان ", pic: "/images/projects/roudan1.png" },
  { id: "43", idProj: "4",name:" تصفیه خانه فاضلاب شهر رودان ", pic: "/images/projects/roudan2.png" },
  { id: "44", idProj: "25",name:" تصفیه خانه فاضلاب شهرک صنعتی شهید سلیمی ", pic: "/images/projects/Salimi1.jpg" },
  { id: "45", idProj: "25",name:" تصفیه خانه فاضلاب شهرک صنعتی شهید سلیمی ", pic: "/images/projects/Salimi2.jpg" },
  { id: "46", idProj: "6",name:" تصفیه خانه آب شهر ساری", pic: "/images/projects/Sari1.png" },
  { id: "47", idProj: "6",name:" تصفیه خانه آب شهر ساری", pic: "/images/projects/Sari2.png" },
  { id: "48", idProj: "14",name:" تلمبه خانه فاضلاب ساری", pic: "/images/projects/Sari21.jpg" },
  { id: "49", idProj: "14",name:" تلمبه خانه فاضلاب ساری", pic: "/images/projects/Sari22.jpg" },
  { id: "50", idProj: "15",name:" تصفیه خانه فاضلاب سمنان", pic: "/images/projects/Semnan1.jpg" },
  { id: "51", idProj: "15",name:" تصفیه خانه فاضلاب سمنان", pic: "/images/projects/Semnan2.jpg" },
  { id: "52", idProj: "24",name:" تصفیه خانه فاضلاب شهرک صنعتی شمس آباد ", pic: "/images/projects/Shams1.jpg" },
  { id: "53", idProj: "24",name:" تصفیه خانه فاضلاب شهرک صنعتی شمس آباد ", pic: "/images/projects/Shams2.jpg" },
  { id: "54", idProj: "1",name:" تصفیه خانه فاضلاب شهر تبریز", pic: "/images/projects/Tabriz1.jpg" },
  { id: "55", idProj: "1",name:" تصفیه خانه فاضلاب شهر تبریز", pic: "/images/projects/Tabriz2.png" },
  { id: "56", idProj: "20",name:" تصفیه خانه آب شهر تکاب", pic: "/images/projects/Takab1.jpg" },
  { id: "57", idProj: "20",name:" تصفیه خانه آب شهر تکاب", pic: "/images/projects/Takab2.jpg" },
  { id: "58", idProj: "20",name:" تصفیه خانه آب شهر تکاب", pic: "/images/projects/Takab3.jpg" },
  { id: "59", idProj: "2",name:" تصفیه خانه فاضلاب تهران مدول 7و8", pic: "/images/projects/Tehran1.jpg" },
  { id: "60", idProj: "2",name:" تصفیه خانه فاضلاب تهران مدول 7و8", pic: "/images/projects/Tehran2.jpg" },
  { id: "61", idProj: "11",name:" تصفیه خانه فاضلاب تویسرکان", pic: "/images/projects/Touser1.png" },
  { id: "62", idProj: "11",name:" تصفیه خانه فاضلاب تویسرکان", pic: "/images/projects/Touser2.png" },
  { id: "63", idProj: "11",name:" تصفیه خانه فاضلاب تویسرکان", pic: "/images/projects/Touser3.png" },
  { id: "64", idProj: "3",name:" تصفیه خانه فاضلاب شهر واوان ", pic: "/images/projects/Vavan1.png" },
  { id: "65", idProj: "3",name:" تصفیه خانه فاضلاب شهر واوان ", pic: "/images/projects/Vavan2.png" },
];
export { PictureData };
