const ProcessStepData = [
  {
    id: "1",
    idProj: "1",
    processStep: "آشغالگیر",
  },
  { id: "2", idProj: "1", processStep: "ایستگاه پمپاژ ورودی" },
  { id: "3", idProj: "1", processStep: "دانه گیری" },
  { id: "4", idProj: "1", processStep: "ته نشینی اولیه " },
  { id: "5", idProj: "1", processStep: "راکتور بیولوژیکی (Step Feed) " },
  { id: "6", idProj: "1", processStep: "ته نشینی ثانویه " },
  { id: "7", idProj: "1", processStep: "کلرزنی (گاز کلر) " },
  { id: "8", idProj: "1", processStep: "تغلیظ کننده ثقلی لجن خام  " },
  { id: "9", idProj: "1", processStep: "تغلیظ کننده نواری لجن اضافی  " },
  { id: "10", idProj: "1", processStep: "آبگیری لجن (فیلتر پرس) " },
  {
    id: "11",
    idProj: "1",
    processStep: "هاضم بی هوازی لجن و سیستم بیوگاز و تاسیسات سولفورزدایی ",
  },
  { id: "12", idProj: "1", processStep: "CHP " },
  {
    id: "13",
    idProj: "1",
    processStep: " ایستگاه پمپاژ لجن اضافی و برگشتی  و لجن هضم شده ",
  },
  { id: "14", idProj: "1", processStep: "ایستگاه پمپاژ سوپرناتانت " },
  { id: "15", idProj: "1", processStep: " ایستگاه پمپاژ لجن غلیظ شده" },
  {
    id: "16",
    idProj: "2",
    processStep: "آشغالگیر",
  },

  {
    id: "17",
    idProj: "2",
    processStep: " دانه گیری",
  },
  {
    id: "18",
    idProj: "2",
    processStep: "ته نشینی اولیه ",
  },
  {
    id: "19",
    idProj: "2",
    processStep: "راکتور بیولوژیکی",
  },
  {
    id: "20",
    idProj: "2",
    processStep: "ته نشینی ثانویه",
  },
  {
    id: "21",
    idProj: "2",
    processStep: "کلرزنی (گاز کلر)",
  },
  {
    id: "22",
    idProj: "2",
    processStep: "تغلیظ کننده ثقلی لجن خام",
  },
  {
    id: "23",
    idProj: "2",
    processStep: "تغلیظ کننده نواری لجن اضافی",
  },
  {
    id: "24",
    idProj: "2",
    processStep: "آبگیری لجن (فیلتر پرس)",
  },
  {
    id: "25",
    idProj: "2",
    processStep: "هاضم بی هوازی لجن و سیستم بیوگاز و تاسیسات سولفورزدایی",
  },
  {
    id: "26",
    idProj: "2",
    processStep: "CHP",
  },
  {
    id: "27",
    idProj: "2",
    processStep: "ایستگاه پمپاژ لجن اضافی و برگشتی  و لجن هضم شده ",
  },
  {
    id: "28",
    idProj: "2",
    processStep: "ایستگاه پمپاژ لجن غلیظ شده",
  },
  { id: "29", idProj: "2", processStep: "ایستگاه پمپاژ سوپرناتانت" },
  {
    id: "30",
    idProj: "3",
    processStep: "آشغالگیر",
  },
  {
    id: "31",
    idProj: "3",
    processStep: "ایستگاه پمپاژ ورودی",
  },
  {
    id: "32",
    idProj: "3",
    processStep: " دانه گیری",
  },
  {
    id: "33",
    idProj: "3",
    processStep: "ته نشینی اولیه ",
  },
  {
    id: "34",
    idProj: "3",
    processStep: "تانک انوکسیک و هوادهی ",
  },
  {
    id: "35",
    idProj: "3",
    processStep: "ته نشینی ثانویه",
  },
  {
    id: "36",
    idProj: "3",
    processStep: "کلرزنی (گاز کلر)",
  },

  {
    id: "37",
    idProj: "3",
    processStep: "تغلیظ کننده نواری لجن ",
  },
  {
    id: "38",
    idProj: "3",
    processStep: "آبگیری لجن (فیلتر پرس)",
  },
  {
    id: "39",
    idProj: "3",
    processStep: "هاضم هوازی لجن",
  },

  {
    id: "40",
    idProj: "3",
    processStep: "ایستگاه پمپاژ لجن اضافی و برگشتی  ",
  },
  {
    id: "41",
    idProj: "3",
    processStep: "ایستگاه پمپاژ کفآب",
  },
  { id: "42", idProj: "3", processStep: "ایستگاه پمپاژ لجن غلیظ شده " },
  { id: "43", idProj: "3", processStep: "ایستگاه پمپاژ لجن هضم شده " },
  {
    id: "44",
    idProj: "4",
    processStep: "آشغالگیر",
  },
  {
    id: "45",
    idProj: "4",
    processStep: "ایستگاه پمپاژ ورودی",
  },
  {
    id: "46",
    idProj: "4",
    processStep: " دانه گیری",
  },
  {
    id: "47",
    idProj: "4",
    processStep: "تانک کاروسل",
  },

  {
    id: "48",
    idProj: "4",
    processStep: "ته نشینی ثانویه",
  },
  {
    id: "49",
    idProj: "4",
    processStep: "کلرزنی (گاز کلر)",
  },
  { id: "50", idProj: "4", processStep: "ایستگاه پمپاژ لجن اضافی و برگشتی  " },
  {
    id: "51",
    idProj: "4",
    processStep: "ایستگاه پمپاژ کفآب",
  },
  { id: "52", idProj: "4", processStep: "ایستگاه پمپاژ لجن غلیظ شده " },
  { id: "53", idProj: "4", processStep: "بسترهای لجن" },
  { id: "54", idProj: "4", processStep: "	تلمبه خانه زهاب " },
  { id: "259", idProj: "4", processStep: "تلمبه خانه کفاب " },
  { id: "55", idProj: "5", processStep: "آشغالگیر" },
  { id: "56", idProj: "5", processStep: "ایستگاه پمپاژ ورودی" },
  { id: "57", idProj: "5", processStep: "دانه گیری" },
  { id: "58", idProj: "5", processStep: "راکتور بیهوازی" },
  { id: "59", idProj: "5", processStep: "راکتور آنوکسیک" },
  { id: "60", idProj: "5", processStep: "راکتور هوادهی " },
  { id: "61", idProj: "5", processStep: "ته نشینی" },
  { id: "62", idProj: "5", processStep: "کلرزنی (گاز کلر)" },
  { id: "63", idProj: "5", processStep: "تغلیظ لجن (تغلیظ کننده ثقلی)" },
  { id: "64", idProj: "5", processStep: "آبگیری لجن (فیلتر پرس)" },
  { id: "65", idProj: "5", processStep: "ایستگاه پمپاژ لجن اضافی و برگشتی" },
  { id: "66", idProj: "5", processStep: "ایستگاه پمپاژ کفاب" },
  { id: "67", idProj: "5", processStep: "ایستگاه پمپاژ لجن غلیظ شده" },
  { id: "68", idProj: "6", processStep: "هوادهی" },
  { id: "69", idProj: "6", processStep: "میکرو استرینر" },
  { id: "70", idProj: "6", processStep: "فرآیند انعقاد " },
  { id: "71", idProj: "6", processStep: "آماده سازی و تزریق مواد شیمیایی" },
  { id: "72", idProj: "6", processStep: "کلاریفلوکولاتور" },
  {
    id: "73",
    idProj: "6",
    processStep:
      "فیلتراسیون (فیلتر دو لایه شن و آنتراسیت با سیستم بکواش هوا و آب)",
  },
  { id: "74", idProj: "6", processStep: "کلرزنی " },
  { id: "75", idProj: "6", processStep: "تغلیظ لجن (ثقلی)" },
  { id: "76", idProj: "6", processStep: "آبگیری لجن (سانتریفیوژ)" },
  {
    id: "77",
    idProj: "6",
    processStep: "واحد بازیافت آب و ایستگاه پمپاژ آب بک واش",
  },
  { id: "78", idProj: "7", processStep: "شیرخانه ورودی آب خام " },
  { id: "79", idProj: "7", processStep: "آشغالگیر " },
  { id: "80", idProj: "7", processStep: "میکرواسترینر" },
  { id: "81", idProj: "7", processStep: "پیش ته نشینی" },
  { id: "82", idProj: "7", processStep: "هوادهی دیفیوزری " },
  { id: "83", idProj: "7", processStep: "حوضچه اختلاط سریع" },
  { id: "84", idProj: "7", processStep: "حوضچه اختلاط کند" },
  { id: "85", idProj: "7", processStep: "ته نشینی مستطیلی با صفحات لاملا" },
  { id: "86", idProj: "7", processStep: "فیلتر دو لایه " },
  { id: "87", idProj: "7", processStep: "کلرزنی و آب نما " },
  { id: "88", idProj: "7", processStep: "مخزن متعادل ساز " },
  { id: "89", idProj: "7", processStep: "واحد ذخیره و تغلیظ ثقلی لجن " },
  { id: "90", idProj: "7", processStep: "واحد آبگیری مکانیکی (فیلترپرس) " },
  { id: "91", idProj: "8", processStep: "هوادهی آبشاری" },
  { id: "92", idProj: "8", processStep: "آشغالگیر" },
  { id: "93", idProj: "8", processStep: "فرآیند انعقاد" },
  { id: "94", idProj: "8", processStep: "آماده سازی و تزریق مواد شیمیایی" },
  { id: "95", idProj: "8", processStep: "ته نشینی شیمیایی مقدماتی " },
  { id: "96", idProj: "8", processStep: "ته نشینی (پولساتور)" },
  {
    id: "97",
    idProj: "8",
    processStep: "فیلتراسیون (فیلتر شنی ثقلی با سیستم بک واش هوا و آب)",
  },
  { id: "98", idProj: "8", processStep: "کلرزنی (گاز کلر)" },
  { id: "99", idProj: "8", processStep: "تغلیظ لجن (ثقلی)" },
  { id: "100", idProj: "8", processStep: "آبگیری لجن (فیلتر پرس)" },
  { id: "101", idProj: "8", processStep: "ایستگاه پمپاژ آب بک واش" },
  { id: "102", idProj: "8", processStep: "ایستگاه پمپاژ لجن غلیظ شده" },
  { id: "103", idProj: "8", processStep: "مخزن 10000 متر مکعبی " },
  { id: "104", idProj: "9", processStep: "آشغالگیر" },
  { id: "105", idProj: "9", processStep: "میکرو استرینر" },
  { id: "106", idProj: "9", processStep: "فرآیند انعقاد" },
  { id: "107", idProj: "9", processStep: "آماده سازی و تزریق مواد شیمیایی" },
  { id: "108", idProj: "9", processStep: "ته نشینی (پولساتور)" },
  {
    id: "109",
    idProj: "9",
    processStep: "فیلتراسیون (فیلتر شنی سریع با سیستم بکواش هوا و آب)",
  },
  {
    id: "110",
    idProj: "9",
    processStep: "کلرزنی (تولید هیپو کلریت سدیم با استفاده از نمک طعام)",
  },
  { id: "111", idProj: "9", processStep: "تغلیظ لجن (ثقلی)" },
  { id: "112", idProj: "9", processStep: "آبگیری لجن (بلت فیلتر پرس)" },
  {
    id: "113",
    idProj: "9",
    processStep: "واحد بازیافت آب و ایستگاه پمپاژ آب بک واش",
  },
  { id: "114", idProj: "9", processStep: "تلمبه خانه لجن غلیظ شده" },
  { id: "115", idProj: "9", processStep: "مخزن 10000 متر مکعبی " },
  { id: "116", idProj: "10", processStep: " ایستگاه پمپاژ ورودی" },
  { id: "117", idProj: "10", processStep: "آشغالگیر" },
  { id: "118", idProj: "10", processStep: "دانه گیری" },
  { id: "119", idProj: "10", processStep: "ته نشینی مقدماتی" },
  { id: "120", idProj: "10", processStep: "راکتور انوکسیک" },
  { id: "121", idProj: "10", processStep: "راکتور هوادهی" },
  { id: "122", idProj: "10", processStep: "ته نشینی ثانویه" },
  { id: "123", idProj: "10", processStep: "میکرو استرینینگ" },
  { id: "124", idProj: "10", processStep: "گندزدایی با UV" },
  { id: "125", idProj: "10", processStep: "آماده سازی شیمیایی" },
  { id: "126", idProj: "10", processStep: "تغلیظ لجن (بلت تیکنر)" },
  { id: "127", idProj: "10", processStep: "آبگیری لجن(سانتریفوژ)" },
  { id: "128", idProj: "10", processStep: "تلمبه خا نه لجن اولیه" },
  { id: "129", idProj: "10", processStep: "تلمبه خانه لجن برگشتی و اضافی" },
  { id: "130", idProj: "10", processStep: "تلمبه خا نه لجن غلیظ شده" },
  { id: "131", idProj: "10", processStep: "تلمبه خا نه آب سرویس" },
  { id: "132", idProj: "11", processStep: "آشغالگیر" },
  {
    id: "133",
    idProj: "11",
    processStep: "لاگون هوادهی ( هوادهی عمقی شناور )",
  },
  { id: "134", idProj: "11", processStep: "ته نشینی" },
  { id: "135", idProj: "11", processStep: "کلرزنی (گاز کلر)" },
  { id: "136", idProj: "11", processStep: "هاضم هوازی (هوادهی عمقی)" },
  { id: "137", idProj: "11", processStep: "ایستگاه پمپاژ لجن برگشتی و اضافی " },
  { id: "138", idProj: "11", processStep: "ایستگاه پمپاژ زهاب " },
  { id: "139", idProj: "12", processStep: "آشغالگیری" },
  { id: "140", idProj: "12", processStep: "واحد چربی گیری API" },
  { id: "141", idProj: "12", processStep: "واحد متعادلسازی" },
  { id: "142", idProj: "12", processStep: "واحد انعقاد و لخته سازی" },
  {
    id: "151",
    idProj: "12",
    processStep: "آبگیری لجن بیولوژیک (بلت فیلتر پرس)",
  },
  { id: "143", idProj: "12", processStep: "واحد چربی گیری DAF" },
  { id: "152", idProj: "12", processStep: "آبگیری لجن شیمیایی (سانتریفوژ)" },
  { id: "144", idProj: "12", processStep: "واحد هوادهی ( هوادهی دیفیوزری)" },
  { id: "153", idProj: "12", processStep: "واحد ته نشینی" },
  {
    id: "145",
    idProj: "12",
    processStep: "واحد فیلتراسیون ( فیلترهای تحت فشار شنی و کربنی) ",
  },
  { id: "146", idProj: "12", processStep: "پکیج تهیه محلول شیمیایی" },
  { id: "154", idProj: "12", processStep: "مخزن نگهداری لجن شیمیایی" },
  { id: "147", idProj: "12", processStep: "تلمبه خانه لجن برگشتی و اضافی" },
  { id: "155", idProj: "12", processStep: "تلمبه خانه لجن و روغن شیمیایی" },
  { id: "148", idProj: "12", processStep: "واحد کلرزنی (کلر مایع)" },
  { id: "156", idProj: "12", processStep: "تلمبه خانه لجن غلیظ شده	" },
  { id: "149", idProj: "12", processStep: "تغلیظ کننده ثقلی" },
  { id: "157", idProj: "12", processStep: "تلمبه خانه لجن هضم شده" },
  { id: "150", idProj: "12", processStep: "هاضم هوازی لجن (هوادهی دیفیوزری)" },
  { id: "158", idProj: "12", processStep: "تلمبه خانه آب سرویس " },
  { id: "159", idProj: "13", processStep: "ایستگاه پمپاژ ورودی" },
  { id: "160", idProj: "13", processStep: "آشغالگیر" },
  { id: "161", idProj: "13", processStep: "دانه گیری" },
  {
    id: "162",
    idProj: "13",
    processStep: "هوادهی ( هواده سطحی دور تند نصب ثابت)",
  },
  { id: "163", idProj: "13", processStep: "ته نشینی" },
  { id: "164", idProj: "13", processStep: "کلر زنی (گاز کلر)" },
  { id: "165", idProj: "13", processStep: "تغلیظ لجن (تغلیظ لجن ثقلی)" },
  { id: "166", idProj: "13", processStep: "خشک کردن لجن (بسترهای خشک کن)" },
  { id: "167", idProj: "13", processStep: "ایستگاه پمپاژ لجن برگشتی و اضافی" },
  { id: "168", idProj: "13", processStep: "ایستگاه پمپاژ زهاب" },
  { id: "169", idProj: "14", processStep: "آشغالگیر" },
  { id: "170", idProj: "14", processStep: "ایستگاه پمپاژ" },
  { id: "171", idProj: "14", processStep: "سیستم حفاظت در مقابل ضربه قوچ" },
  { id: "172", idProj: "15", processStep: "آشغالگیر" },
  { id: "173", idProj: "15", processStep: "لاگون هوادهی ( با هواده دور تند)" },
  { id: "174", idProj: "15", processStep: "لاگون ته نشینی" },
  { id: "175", idProj: "15", processStep: "کلرزنی (گاز کلر)" },
  { id: "176", idProj: "16", processStep: "دانه گیری" },
  {
    id: "177",
    idProj: "16",
    processStep: "لاگون هوادهی (هوادهی سطحی  دور تند نصب ثابت)",
  },
  { id: "178", idProj: "16", processStep: "لاگون ته نشینی" },
  { id: "179", idProj: "16", processStep: "کلرزنی (گاز کلر)" },
  { id: "180", idProj: "17", processStep: "ایستگاه پمپاژ ورودی" },
  { id: "181", idProj: "17", processStep: "آشغالگیر" },
  { id: "182", idProj: "17", processStep: "دانه گیری" },
  {
    id: "183",
    idProj: "17",
    processStep: "هوادهی ( هواده سطحی دور تند نصب ثابت)",
  },
  { id: "184", idProj: "17", processStep: "ته نشینی" },
  { id: "185", idProj: "17", processStep: "کلر زنی (گاز کلر)" },
  { id: "186", idProj: "17", processStep: "تغلیظ لجن (تغلیظ لجن ثقلی)" },
  { id: "187", idProj: "17", processStep: "خشک کردن لجن (بسترهای خشک کن)" },
  { id: "188", idProj: "17", processStep: "ایستگاه پمپاژ لجن برگشتی و اضافی" },
  { id: "189", idProj: "17", processStep: "ایستگاه پمپاژ زهاب" },
  { id: "190", idProj: "18", processStep: "آشغالگیر" },
  { id: "191", idProj: "18", processStep: "دانه گیری" },
  {
    id: "192",
    idProj: "18",
    processStep: "لاگون هوادهی (هوا دهی سطحی دور تند شناور)",
  },
  { id: "193", idProj: "18", processStep: "لاگون ته نشینی" },
  { id: "194", idProj: "18", processStep: "کلرزنی (گاز کلر)" },
  { id: "195", idProj: "19", processStep: "آشغالگیر" },
  {
    id: "196",
    idProj: "19",
    processStep: "لاگون هوادهی ( هواده دور تند و دور کند نصب ثابت)",
  },
  { id: "197", idProj: "19", processStep: "لاگون های ته نشینی" },
  { id: "198", idProj: "19", processStep: "کلرزنی (گاز کلر)" },
  { id: "199", idProj: "20", processStep: "ته نشینی مقدماتی" },
  { id: "200", idProj: "20", processStep: "فرآیند انعقاد (فلش میکسر)" },
  { id: "201", idProj: "20", processStep: "آماده سازی و تزریق مواد شیمیایی" },
  { id: "202", idProj: "20", processStep: "ته نشینی (پولساتور)" },
  {
    id: "203",
    idProj: "20",
    processStep: "فیلتراسیون (فیلتر شنی ثقلی با سیستم بک واش آب و هوا)",
  },
  { id: "204", idProj: "20", processStep: "کلرزنی اولیه و ثانویه (گاز کلر)" },
  { id: "205", idProj: "20", processStep: "ایستگاه پمپاژ آب بازیافت" },
  { id: "206", idProj: "21", processStep: "ایستگاه پمپاژ ورودی" },
  { id: "207", idProj: "21", processStep: "آشغالگیر" },
  {
    id: "208",
    idProj: "21",
    processStep: "لاگون هوادهی (هواده سطحی دورکندنصب ثابت)",
  },
  { id: "209", idProj: "21", processStep: "لاگون ته نشینی" },
  { id: "210", idProj: "21", processStep: "کلر زنی (گاز کلر)" },
  {
    id: "211",
    idProj: "22",
    processStep: "فیلتراسیون مستقیم (فیلتر شنی تحت فشار)",
  },
  { id: "212", idProj: "22", processStep: "کلرزنی اولیه و ثانویه (گاز کلر)" },
  { id: "213", idProj: "23", processStep: "آشغالگیر" },
  { id: "214", idProj: "23", processStep: "متعادلسازی" },
  { id: "215", idProj: "23", processStep: "هوادهی" },
  { id: "216", idProj: "23", processStep: "ته نشینی ثقلی " },
  { id: "217", idProj: "23", processStep: "کلرزنی (کلر مایع)" },
  { id: "218", idProj: "23", processStep: "تغلیظ لجن ثقلی" },
  { id: "219", idProj: "23", processStep: "آبگیری لجن (بستر های لجن خشک کن)" },
  { id: "220", idProj: "24", processStep: "ایستگاه پمپاژ" },
  { id: "221", idProj: "24", processStep: "آشغالگیر" },
  {
    id: "222",
    idProj: "24",
    processStep: "لاگون هوادهی (هواده سطحی  دور تند شناور )",
  },
  { id: "223", idProj: "24", processStep: "لاگون ته نشینی" },
  { id: "224", idProj: "24", processStep: "کلرزنی (کلر مایع)" },
  { id: "225", idProj: "25", processStep: "آشغالگیر" },
  { id: "226", idProj: "25", processStep: "ایستگاه پمپاژ ورودی" },
  { id: "227", idProj: "25", processStep: "واحد چربی گیری API" },
  { id: "228", idProj: "25", processStep: "تانک متعادل سازی" },
  { id: "229", idProj: "25", processStep: "ته نشینی شیمیایی" },
  { id: "230", idProj: "25", processStep: "انتخابگر بیولوژیکی" },
  { id: "231", idProj: "25", processStep: "هوادهی ( هواده دور کند نصب ثابت)" },
  { id: "232", idProj: "25", processStep: "ته نشینی" },
  { id: "233", idProj: "25", processStep: "کلرزنی (کلر مایع)" },
  { id: "234", idProj: "25", processStep: "تغلیظ لجن (تغلیظ ثقلی)" },
  { id: "235", idProj: "25", processStep: "هاضم  هوازی" },
  { id: "236", idProj: "25", processStep: "خشک کننده لجن (بسترهای خشک کن)" },
  { id: "237", idProj: "25", processStep: "ایستگاه پمپاژ لجن خام" },
  { id: "238", idProj: "25", processStep: "ایستگاه پمپاژ لجن اضافی و برگشتی" },
  { id: "239", idProj: "26", processStep: "آشغالگیر" },
  { id: "240", idProj: "26", processStep: "ایستگاه پمپاژ ورودی" },
  { id: "241", idProj: "26", processStep: "متعادل سازی" },
  { id: "242", idProj: "26", processStep: "فرآیند انعقاد" },
  { id: "243", idProj: "26", processStep: "فرآیند لخته سازی" },
  { id: "244", idProj: "26", processStep: "آماده سازی و تزریق مواد شیمیایی" },
  { id: "245", idProj: "26", processStep: "ته نشینی شیمیایی" },
  { id: "246", idProj: "26", processStep: "ایستگاه پمپاژ لجن شمیایی" },
  { id: "247", idProj: "26", processStep: "تانک ذخیره لجن شیمیایی" },
  { id: "248", idProj: "26", processStep: "هوادهی (هواده دور تند نصب ثابت)" },
  { id: "249", idProj: "26", processStep: "ته نشینی" },
  { id: "250", idProj: "26", processStep: "کلرزنی (کلر مایع)" },
  { id: "251", idProj: "26", processStep: "فیلتراسیون" },
  { id: "252", idProj: "26", processStep: "فیلتر شنی تحت فشار" },
  { id: "253", idProj: "26", processStep: "فیلترهای کربن فعال" },
  { id: "254", idProj: "26", processStep: "ایستگاه پمپاژ لجن اضافی و برگشتی" },
  { id: "255", idProj: "26", processStep: "هضم کننده هوازی" },
  {
    id: "256",
    idProj: "27",
    processStep:
      "اجرای خط لوله فولادی و پلی اتیلن از قطر 400 تا 700 با فشار کار 25 بار",
  },
  { id: "257", idProj: "27", processStep: "حوضچه شیرآلات " },
  { id: "258", idProj: "27", processStep: "احداث راه دسترسی کنار خط انتقال  " },
];
export { ProcessStepData };
