const ProjData = [
  {
    id: "1",
    name: " تصفیه خانه آب شهر بم",
    employer: "شرکت آب منطقه ای کرمان",
    consultant: "شرکت مهندسین مشاور توس آب",
    contractor: "شرکت مهندسی دزون، شرکت بردو",
    typeOfContract: "PC",
    capacity: "  129600",
    location: "شهر بم",
    process: "none",
    Status: "active",
    supply: "1",
  },
  {
    id: "2",
    name: " تصفیه خانه آب شهر میانه",
    employer: "شرکت آب منطقه ای آذربایجان شرقی",
    consultant: "شرکت مهندسین مشاور آبران",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "EPC",
    capacity: "  38880",
    location: "شهر میانه",
    process: "فیلتراسیون متعارف",
    Status: "Inactive",
    supply: "1",
  },
  {
    id: "3",
    name: " تصفیه خانه فاضلاب شهر تبریز",
    employer: "شرکت آب و فاضلاب آذربایجان شرقی",
    consultant: " شرکت مهندسین مشاور فرازآب",
    contractor: "شرکت مهندسی دزون،شرکت نصر اصفهان ، مهندسین مشاورطوس آب",
    typeOfContract: "EPC",
    capacity: "  207475 ",
    location: "شهرتبریز",
    process: " لجن فعال step feed",
    Status: "active",
    supply: "1",
  },
  {
    id: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    employer: "شرکت فاضلاب تهران",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    contractor: "شرکت مهندسی دزون، شرکت نصر سپهر ، شرکت پایندآب کوشا",
    typeOfContract: "EPC",
    capacity: "319680  ",
    location: "شهرتهران",
    process: " لجن فعال A2O ",

    Status: "active",
    supply: "1",
  },
  {
    id: "5",
    name: " تصفیه خانه فاضلاب شهر واوان ",
    employer: "شرکت آب و فاضلاب جنوب غرب استان تهران ",
    consultant: "شرکت مهندسین مشاور آبران",
    contractor: "شرکت مهندسی دزون ، شرکت بردو",
    typeOfContract: "PC",
    capacity: "40000    ",
    location: "اسلامشهر – واوان",
    process: "لجن فعال MLE",
    Status: "active",
    supply: "1",
  },
  {
    id: "6",
    name: " تصفیه خانه آب شهر ساری",
    employer: "شرکت آب منطقه ای مازندران ",
    consultant: " شرکت مهندسین مشاور ری آب ",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "EPC",
    capacity: "129600   ",
    location: "شهر ساری",
    process: " فیلتراسیون متعارف ",
    Status: "active",
    supply: "1",
  },
  {
    id: "7",
    name: " تصفیه خانه آب شهر خلخال",
    employer: "شرکت آب منطقه ای اردبیل- شرکت طرح و پالایش آب خلخال",
    consultant: "شرکت مهندسین مشاور آبران",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "BOT",
    capacity: "  12312",
    location: "شهر خلخال",
    process: " فیلتراسیون متعارف ",
    Status: "Inactive",
    supply: "0",
  },
  {
    id: "8",
    name: " تصفیه خانه فاضلاب شهر محمود آباد",
    employer: "شرکت آب و فاضلاب استان قزوین",
    consultant: "شرکت مهندسین مشاور آرنا",
    contractor: "شرکت مهندسی دزون، شرکت بردو",
    typeOfContract: "BOT",
    capacity: " 7334   ",
    location: "شهرمحمود آباد",
    process: " لجن فعال A20 ",
    Status: "Inactive",
    supply: "1",
  },
  {
    id: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    employer: "شرکت آب و فاضلاب استان هرمزگان",
    consultant: "شرکت مهندسین مشاور پارس آب تدبیر",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "EPC",
    capacity: "  10886",
    location: "شهررودان",
    process: " لجن فعال کاروسل",
    Status: "Inactive",
    supply: "1",
  },
  {
    id: "10",
    name: "آبرسانی به صنایع  مستقر در ایجرود از سد گلابر شهرستان ایجرود",
    employer: "آب منطقه ای زنجان ",
    consultant: "شرکت مهندسین ارکاب رهاب ",
    contractor: "شرکت مهندسی دزون ",
    typeOfContract: "PC",
    location: "شهر ایجرود – زنجان ",
    process: "none",
    Status: "Inactive",
    supply: "0",
  },
  {
    id: "11",
    name: " تصفیه خانه فاضلاب صنایع لاستیک تایر کرد",
    employer: "شرکت صنایع لاستیک تایر کرد",
    consultant: "شرکت مهندسین مشاور سازه",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "EPC",
    capacity: "  576",
    location: "شهر زنجان",
    process: " پیش تصفیه شیمیایی – لجن فعال ",
    Status: "Inactive",
    supply: "0",
  },
  {
    id: "12",
    name: " تصفیه خانه فاضلاب شهرک صنعتی شهید سلیمی ",
    employer: "شرکت شهرک صنعتی ایران",
    consultant: "شرکت مهندسین مهاب قدس",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "EPC",
    Capacity: "  5280",
    location: "شهرک صنعتی شهید سلیمی",
    process: " پیش تصفیه شیمیایی – لجن فعال ",
    Status: "Inactive",
    supply: "0",
  },
  {
    id: "13",
    name: " تصفیه خانه فاضلاب شهرک صنعتی شمس آباد ",
    employer: "شرکت شهرک صنعتی تهران",
    consultant: "شرکت مهندسی به آب زیست",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "EPC",
    Capacity: "",
    location: "شهرک صنعتی شمس آباد",
    process: "لاگون هوادهی",
    Status: "Inactive",
    supply: "0",
  },
  {
    id: "14",
    name: " تصفیه خانه فاضلاب بهارستان",
    employer: "شرکت آب و فاضلاب بهارستان",
    consultant: "شرکت مهندسین مشاور طرح و تحقیقات آب و فاضلاب ",
    contractor: "شرکت مهندسی دزون ",
    typeOfContract: "EPC",
    capacity: "  46656",
    location: " شهر بهارستان اصفهان",
    process: " لجن فعالMLE",
    Status: "Inactive",
    supply: "1",
  },
  {
    id: "15",
    name: " تصفیه خانه فاضلاب شهرک صنعتی بهارستان",
    employer: "شهرک صنعتی بهارستان",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "EPC",
    Capacity: "",
    location: "شهرک صنعتی بهارستان",
    process: " لجن فعال ",
    Status: "Inactive",
    supply: "0",
  },
  {
    id: "16",
    name: " تصفیه خانه اضطراری آب عباس آباد همدان",
    employer: "شرکت آب و فاضلاب همدان",
    consultant: "شرکت مهندسین مشاور مشارآب",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "EPC",
    capacity: "  21600",
    location: "شهر همدان",
    process: " فیلتراسیون مستقیم",

    Status: "Inactive",
    supply: "0",
  },
  {
    id: "17",
    name: " تصفیه خانه فاضلاب شهر اردبیل",
    employer: "شرکت آب و فاضلاب اردبیل",
    consultant: "مهندسین مشاور مهاب قدس",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "PC",
    capacity: "  18360 ",
    Location: " شهر اردبیل",
    Process: " لاگون هوادهی",
    Status: "Inactive",
    supply: "0",
  },
  {
    id: "18",
    name: " تصفیه خانه آب شهر تکاب",
    employer: "شرکت سهامی آب منطقه ای آذربایجان غربی ",
    consultant: "شرکت مهندسین مشاور آشناب",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "PC",
    capacity: "  28920",
    location: "شهر تکاب",
    Process: "فیلتراسیون متعارف ",
    Status: "Inactive",
    supply: "1",
  },
  {
    id: "19",
    name: " تصفیه خانه فاضلاب شهر مهاباد",
    employer: "شرکت آب و فاضلاب آذربایجان غربی",
    consultant: "شرکت مهندسین مشاور آشناب",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "PC",
    capacity: "  78840 ",
    location: "شهر مهاباد",
    process: " لاگون های هوادهی",
    Status: "Inactive",
    supply: "0",
  },
  {
    id: "20",
    name: " تصفیه خانه فاضلاب شهر بندر گز",
    employer: "شرکت آب و فاضلاب گلستان",
    consultant: "شرکت مهندسین مشاور پژوهاب",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "PC",
    capacity: "8640",
    location: "شهر بندر گز",
    process: " لاگون های هوادهی",
    Status: "Inactive",
    supply: "1",
  },
  {
    id: "21",
    name: " تصفیه خانه فاضلاب دزفول",
    employer: "شرکت آب و فاضلاب استان خوزستان",
    consultant: "شرکت مهندسین مشاور ری آب",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "PC",
    capacity: "38016",
    location: "شهردزفول",
    process: " لاگون های هوادهی",
    Status: "Inactive",
    supply: "1",
  },
  {
    id: "22",
    name: " تصفیه خانه فاضلاب سمنان",
    employer: "شرکت آب و فاضلاب سمنان",
    consultant: "شرکت مهندسین مشاور آبران",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "PC",
    capacity: "  35400",
    location: "شهر سمنان",
    process: " لاگون های هوادهی",
    Status: "Inactive",
    supply: "0",
  },
  {
    id: "23",
    name: " تلمبه خانه فاضلاب ساری",
    employer: "شرکت آب و فاضلاب مازندران",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: " EPC",
    capacity: "  92016",
    location: "شهر ساری",
    process: "none",
    Status: "Inactive",
    supply: "0",
  },
  {
    id: "24",
    name: " تصفیه خانه فاضلاب شهر کردکوی",
    employer: "شرکت آب و فاضلاب گلستان",
    consultant: "شرکت مهندسین مشاور پژوهاب",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "PC",
    capacity: "  18120 ",
    location: "شهر کردکوی",
    process: " لجن فعال هوادهی گسترده",
    Status: "Inactive",
    supply: "1",
  },
  {
    id: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    employer: "شرکت مبین پتروشیمی ",
    consultant: "شرکت مهندسین مشاور سازه",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "EPC",
    capacity: "  10200",
    location: "شهرک صنعتی عسلویه",
    process: " پیش تصفیه شیمیایی و لجن فعال ",
    Status: "Inactive",
    supply: "1",
  },
  {
    id: "26",
    name: " تصفیه خانه فاضلاب تویسرکان",
    employer: "شرکت آب و فاضلاب استان همدان ",
    consultant: "شرکت مهندسین مشاور موج آب",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: "EPC",
    capacity: "  25920",
    location: "شهر تویسرکان",
    process: " لاگون هوادهی اختلاط کامل",
    Status: "Inactive",
    supply: "0",
  },
  {
    id: "27",
    name: " تلمبه خانه برداشت آب از سد جگین  ",
    employer: "شرکت آب و فاضلاب استان هرمزگان ",
    consultant: "شرکت مهندسین مشاور ری آب ",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: " EPC",
    capacity: " 73440",
    location: " سد جگین ",
    process: "none",
    Status: "Inactive",
    supply: "0",
  },
  {
    id: "28",
    name: " تصفیه خانه فاضلاب سامان",
    employer: " شرکت آب فاضلاب استان چهار محال و بختیاری ",
    consultant: " شرکت مهندسین مشاور طرح و تحقیقات آب و فاضلاب ",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: " PC",
    capacity: "  10440",
    location: " شهر سامان ",
    process: " لاگون هوادهی ",
    Status: "Inactive",
    supply: "0",
  },
  {
    id: "29",
    name: " تصفیه خانه فاضلاب شهر پاوه ",
    employer: " شرکت آب  فاضلاب استان کرمانشاه ",
    consultant: " شرکت مهندسین مشاور جویاب نو ",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: " PC",
    capacity: "15960",
    location: "شهر پاوه ",
    process: " لجن فعال به روش هوادهی گسترده ",
    Status: "Inactive",
    supply: "0",
  },
  {
    id: "30",
    name: " تصفیه خانه فاضلاب عجب شیر ",
    employer: "شرکت آب و فاضلاب استان آذربایجان شرقی ",
    consultant: "شرکت مهندسین مشاور آشناب ",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: " PC",
    capacity: "  27120",
    location: "شهر عجب شیر ",
    process: " لجن فعال به روش هوادهی گسترده  ",
    Status: "Inactive",
    supply: "0",
  },
  {
    id: "31",
    name: " تصفیه خانه فاضلاب ملایر",
    employer: "شرکت آب  فاضلاب استان همدان  ",
    consultant: "شرکت مهندسین مشاور ری آب ",
    contractor: "شرکت مهندسی دزون",
    typeOfContract: " PC",
    capacity: "  43200",
    location: "شهر ملایر ",
    process: " لاگون هوادهی اختلاط کامل ",
    Status: "Inactive",
    supply: "0",
  },
  {
    id: "32",
    name: "آبگیر شناور طرح آبرسانی به شهر جهرم از سد سلمان فارسی ",
    employer: "شرکت آب منطقه ای فارس ",
    consultant: "شرکت مهندسین مشاور پارس فراز بند ",
    contractor: "شرکت مهندسی دزون، شرکت بردو، شرکت طوس آب ",
    typeOfContract: " EPC",
    capacity: " 500",
    location: "شهر جهرم  ",
    process: "none",
    Status: "Inactive",
    supply: "0",
  },
];

export { ProjData };
