const ProjSupp = [
{id:"1",idProj:"1",name:" تصفیه خانه فاضلاب شهر تبریز",employer:"شرکت آب و فاضلاب آذربایجان شرقی",consultant:" شرکت مهندسین مشاور فرازآب",materiel:"آشغالگیر مکانیکی دهانه درشت",compan:"SERECO-ITALY"},
{id:"2",idProj:"1",name:" تصفیه خانه فاضلاب شهر تبریز",employer:"شرکت آب و فاضلاب آذربایجان شرقی",consultant:" شرکت مهندسین مشاور فرازآب",materiel:"آشغالگیر مکانیکی دهانه ریز",compan:"SERECO-ITALY"},
{id:"3",idProj:"1",name:" تصفیه خانه فاضلاب شهر تبریز",employer:"شرکت آب و فاضلاب آذربایجان شرقی",consultant:" شرکت مهندسین مشاور فرازآب",materiel:"کلاسیفایر شستشوی دانه",compan:"SERECO-ITALY"},
{id:"4",idProj:"1",name:" تصفیه خانه فاضلاب شهر تبریز",employer:"شرکت آب و فاضلاب آذربایجان شرقی",consultant:" شرکت مهندسین مشاور فرازآب",materiel:"اسکروپمپ",compan:"REHART-GERMANY"},
{id:"5",idProj:"1",name:" تصفیه خانه فاضلاب شهر تبریز",employer:"شرکت آب و فاضلاب آذربایجان شرقی",consultant:" شرکت مهندسین مشاور فرازآب",materiel:"دیفیوزر",compan:"EDI-USA"},
{id:"6",idProj:"1",name:" تصفیه خانه فاضلاب شهر تبریز",employer:"شرکت آب و فاضلاب آذربایجان شرقی",consultant:" شرکت مهندسین مشاور فرازآب",materiel:"بلوئر ",compan:"AERZEN-GERMANY"},
{id:"7",idProj:"1",name:" تصفیه خانه فاضلاب شهر تبریز",employer:"شرکت آب و فاضلاب آذربایجان شرقی",consultant:" شرکت مهندسین مشاور فرازآب",materiel:"پمپ های مستغرق ",compan:"KSB-GERMANY"},
{id:"8",idProj:"1",name:" تصفیه خانه فاضلاب شهر تبریز",employer:"شرکت آب و فاضلاب آذربایجان شرقی",consultant:" شرکت مهندسین مشاور فرازآب",materiel:"خردکن لجن ",compan:"SEEPEX-GERMANY"},
{id:"9",idProj:"1",name:" تصفیه خانه فاضلاب شهر تبریز",employer:"شرکت آب و فاضلاب آذربایجان شرقی",consultant:" شرکت مهندسین مشاور فرازآب",materiel:"میکسرهای مستغرق ",compan:"KSB-GERMANY"},
{id:"10",idProj:"1",name:" تصفیه خانه فاضلاب شهر تبریز",employer:"شرکت آب و فاضلاب آذربایجان شرقی",consultant:" شرکت مهندسین مشاور فرازآب",materiel:"دستگاه تغلیظ مکانیکی و آبگیری مکانیکی ",compan:"ANDRITZ-FRANCE"},
{id:"11",idProj:"1",name:" تصفیه خانه فاضلاب شهر تبریز",employer:"شرکت آب و فاضلاب آذربایجان شرقی",consultant:" شرکت مهندسین مشاور فرازآب",materiel:"پکیج تهیه محلول مواد شیمیایی ",compan:"PROMINET-GERMANY"},
{id:"12",idProj:"1",name:" تصفیه خانه فاضلاب شهر تبریز",employer:"شرکت آب و فاضلاب آذربایجان شرقی",consultant:" شرکت مهندسین مشاور فرازآب",materiel:"پمپ های گریز از مرکز ",compan:"SEEPEX-GERMANY"},
{id:"13",idProj:"1",name:" تصفیه خانه فاضلاب شهر تبریز",employer:"شرکت آب و فاضلاب آذربایجان شرقی",consultant:" شرکت مهندسین مشاور فرازآب",materiel:"کمپرسور ",compan:"FINI-ITALY"},
{id:"14",idProj:"1",name:" تصفیه خانه فاضلاب شهر تبریز",employer:"شرکت آب و فاضلاب آذربایجان شرقی",consultant:" شرکت مهندسین مشاور فرازآب",materiel:"تجهیزات هضم لجن ",compan:"ENNOX-AUSTRIA"},
{id:"15",idProj:"1",name:" تصفیه خانه فاضلاب شهر تبریز",employer:"شرکت آب و فاضلاب آذربایجان شرقی",consultant:" شرکت مهندسین مشاور فرازآب",materiel:"مخازن ذخیره سازی بیوگاز",compan:" AAT-GERMANY"},
{id:"16",idProj:"1",name:" تصفیه خانه فاضلاب شهر تبریز",employer:"شرکت آب و فاضلاب آذربایجان شرقی",consultant:" شرکت مهندسین مشاور فرازآب",materiel:"دستگاه CHP",compan:"MWM GERMANY-"},
{id:"17",idProj:"2",name:" تصفیه خانه فاضلاب تهران مدول 7و8",employer:"شرکت فاضلاب تهران",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"آشغالگیر مکانیکی دهانه درشت",compan:" EMO/GERMANY"},
{id:"18",idProj:"2",name:" تصفیه خانه فاضلاب تهران مدول 7و8",employer:"شرکت فاضلاب تهران",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"آشغالگیر مکانیکی دهانه ریز",compan:" EMO/GERMANY"},
{id:"19",idProj:"2",name:" تصفیه خانه فاضلاب تهران مدول 7و8",employer:"شرکت فاضلاب تهران",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"کلاسیفایر",compan:" EMO/GERMANY"},
{id:"20",idProj:"2",name:" تصفیه خانه فاضلاب تهران مدول 7و8",employer:"شرکت فاضلاب تهران",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"کامپکتور آشغال ",compan:"EMO/GERMANY"},
{id:"21",idProj:"2",name:" تصفیه خانه فاضلاب تهران مدول 7و8",employer:"شرکت فاضلاب تهران",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"کانوایر آشغال ",compan:"EMO/GERMANY"},
{id:"22",idProj:"2",name:" تصفیه خانه فاضلاب تهران مدول 7و8",employer:"شرکت فاضلاب تهران",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"بلوئر دانه گیر ",compan:"AERZEN/GERMANY"},
{id:"23",idProj:"2",name:" تصفیه خانه فاضلاب تهران مدول 7و8",employer:"شرکت فاضلاب تهران",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"بلوئر هوادهی ",compan:"NEXTTURBO/ITALY"},
{id:"24",idProj:"2",name:" تصفیه خانه فاضلاب تهران مدول 7و8",employer:"شرکت فاضلاب تهران",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"میکسر مستغرق ",compan:" KSB/GERMANY"},
{id:"25",idProj:"2",name:" تصفیه خانه فاضلاب تهران مدول 7و8",employer:"شرکت فاضلاب تهران",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"پمپهای لجن ",compan:"KSB/GERMANY"},
{id:"26",idProj:"2",name:" تصفیه خانه فاضلاب تهران مدول 7و8",employer:"شرکت فاضلاب تهران",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"دبفیوزر ",compan:"SUPRATEC/GERMAN"},
{id:"27",idProj:"6",name:" تصفیه خانه آب شهر ساری",employer:"شرکت آب منطقه ای مازندران ",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"میکرو فیلتر )میکرو استرینر) ",compan:"NORDIC WATER -SWEDEN"},
{id:"28",idProj:"6",name:" تصفیه خانه آب شهر ساری",employer:"شرکت آب منطقه ای مازندران ",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"سیستم کلرزنی ",compan:" ALLDOS -GERMANY"},
{id:"29",idProj:"6",name:" تصفیه خانه آب شهر ساری",employer:"شرکت آب منطقه ای مازندران ",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"دستگاه سانتریفوژ آبگیری لجن",compan:"ANDRITZ – FRANCE"},
{id:"30",idProj:"6",name:" تصفیه خانه آب شهر ساری",employer:"شرکت آب منطقه ای مازندران ",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"پمپ هلیکال روتور ",compan:"SEEPEX –GERMANY"},
{id:"31",idProj:"6",name:" تصفیه خانه آب شهر ساری",employer:"شرکت آب منطقه ای مازندران ",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"الکتروپمپ های سانتریفیوژ ",compan:"KSB-GERMANY"},
{id:"32",idProj:"6",name:" تصفیه خانه آب شهر ساری",employer:"شرکت آب منطقه ای مازندران ",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"پکیج تزریق مواد شیمیایی ",compan:"ANDRITZ – FRANCE"},
{id:"33",idProj:"6",name:" تصفیه خانه آب شهر ساری",employer:"شرکت آب منطقه ای مازندران ",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"بلوئرهای هوادهی ",compan:"AERZEN-GERMANY"},
{id:"34",idProj:"6",name:" تصفیه خانه آب شهر ساری",employer:"شرکت آب منطقه ای مازندران ",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"دیفیوزرهای هوادهی ",compan:"EDI-USA"},
{id:"35",idProj:"6",name:" تصفیه خانه آب شهر ساری",employer:"شرکت آب منطقه ای مازندران ",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"شیرآلات برقی و بادی ",compan:"BRAY –ENGLAND "},
{id:"36",idProj:"6",name:" تصفیه خانه آب شهر ساری",employer:"شرکت آب منطقه ای مازندران ",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"گیربکس  ",compan:"NORD-GERMANY"},
{id:"37",idProj:"6",name:" تصفیه خانه آب شهر ساری",employer:"شرکت آب منطقه ای مازندران ",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"الکتروموتور  ",compan:"SIEMENS-GERMANY"},
{id:"38",idProj:"6",name:" تصفیه خانه آب شهر ساری",employer:"شرکت آب منطقه ای مازندران ",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"مرکز دوران پلهای لجن  ",compan:"Rothe-Erde –GERMANY"},
{id:"39",idProj:"6",name:" تصفیه خانه آب شهر ساری",employer:"شرکت آب منطقه ای مازندران ",consultant:"شرکت مهندسین مشاور مهاب قدس",materiel:"تجهیزات کنترل و ابزار دقیق  ",compan:"E&H –GERMANY"},
{id:"40",idProj:"12",name:" تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",employer:"شرکت مبین پتروشیمی – شرکت پتروصنعت اصفهان ", consultant:"شرکت مهندسین سازه",materiel:"الکتروپمپ های مستغرق ",compan:"KSB-GERMANY"},
{id:"41",idProj:"12",name:" تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",employer:"شرکت مبین پتروشیمی – شرکت پتروصنعت اصفهان ", consultant:"شرکت مهندسین سازه",materiel:"میکسرهای مستغرق ",compan:"KSB-GERMANY"},
{id:"42",idProj:"12",name:" تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",employer:"شرکت مبین پتروشیمی – شرکت پتروصنعت اصفهان ", consultant:"شرکت مهندسین سازه",materiel:"پمپ هلیکال روتور ",compan:"NETZSCH –GERMANY"},
{id:"43",idProj:"12",name:" تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",employer:"شرکت مبین پتروشیمی – شرکت پتروصنعت اصفهان ", consultant:"شرکت مهندسین سازه",materiel:"الکتروموتور ",compan:"SIEMENS-GERMANY"},
{id:"44",idProj:"12",name:" تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",employer:"شرکت مبین پتروشیمی – شرکت پتروصنعت اصفهان ", consultant:"شرکت مهندسین سازه",materiel:"دیفیوزرهای هوادهی ",compan:"EDI-USA"},
{id:"45",idProj:"12",name:" تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",employer:"شرکت مبین پتروشیمی – شرکت پتروصنعت اصفهان ", consultant:"شرکت مهندسین سازه",materiel:"بلوئرهای هوادهی",compan:"AERZEN-GERMANY"},
{id:"46",idProj:"12",name:" تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",employer:"شرکت مبین پتروشیمی – شرکت پتروصنعت اصفهان ", consultant:"شرکت مهندسین سازه",materiel:"پکیج تزریق مواد شیمیایی",compan:"MILTONROY-FRANCE"},
{id:"47",idProj:"12",name:" تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",employer:"شرکت مبین پتروشیمی – شرکت پتروصنعت اصفهان ", consultant:"شرکت مهندسین سازه",materiel:"دستگاه سانتریفوژ آبگیری ",compan:"ANDRITZ-FRANCE"},
{id:"48",idProj:"12",name:" تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",employer:"شرکت مبین پتروشیمی – شرکت پتروصنعت اصفهان ", consultant:"شرکت مهندسین سازه",materiel:" شیرآلات برقی ",compan:"VACTRA –ITALY"},
{id:"49",idProj:"12",name:" تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",employer:"شرکت مبین پتروشیمی – شرکت پتروصنعت اصفهان ", consultant:"شرکت مهندسین سازه",materiel:"گیربکس ",compan:"NORD-GERMANY"},
{id:"50",idProj:"12",name:" تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",employer:"شرکت مبین پتروشیمی – شرکت پتروصنعت اصفهان ", consultant:"شرکت مهندسین سازه",materiel:"مرکز دوران پلهای لجن ",compan:"Rothe-Erde –GERMANY"},
{id:"51",idProj:"12",name:" تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",employer:"شرکت مبین پتروشیمی – شرکت پتروصنعت اصفهان ", consultant:"شرکت مهندسین سازه",materiel:" 3 ابزار دقیق",compan:"E&H –GERMANY"},
{id:"52",idProj:"5",name:" تصفیه خانه فاضلاب شهر محمود آباد",employer:"شرکت آب و فاضلاب استان قزوین",consultant:"شرکت مهندسین مشاور آرنا",materiel:"الکترو4پمپ های مستغرق ",compan:"KSB-GERMANY"},
{id:"53",idProj:"5",name:" تصفیه خانه فاضلاب شهر محمود آباد",employer:"شرکت آب و فاضلاب استان قزوین",consultant:"شرکت مهندسین مشاور آرنا",materiel:"میک5سرهای مستغرق",compan:"KSB-GERMANY"},
{id:"54",idProj:"5",name:" تصفیه خانه فاضلاب شهر محمود آباد",employer:"شرکت آب و فاضلاب استان قزوین",consultant:"شرکت مهندسین مشاور آرنا",materiel:"الکتروموتور",compan:"SIEMENS-GERMANY"},
{id:"55",idProj:"5",name:" تصفیه خانه فاضلاب شهر محمود آباد",employer:"شرکت آب و فاضلاب استان قزوین",consultant:"شرکت مهندسین مشاور آرنا",materiel:"دیفیوزرهای هوادهی",compan:"EDI-USA"},
{id:"56",idProj:"5",name:" تصفیه خانه فاضلاب شهر محمود آباد",employer:"شرکت آب و فاضلاب استان قزوین",consultant:"شرکت مهندسین مشاور آرنا",materiel:"بلوئرهای هوادهی",compan:"AERZENE-GERMANY"},
{id:"57",idProj:"5",name:" تصفیه خانه فاضلاب شهر محمود آباد",employer:"شرکت آب و فاضلاب استان قزوین",consultant:"شرکت مهندسین مشاور آرنا",materiel:"سیستم کلرزنی",compan:"ALLDOS-GERMANY"},
{id:"58",idProj:"5",name:" تصفیه خانه فاضلاب شهر محمود آباد",employer:"شرکت آب و فاضلاب استان قزوین",consultant:"شرکت مهندسین مشاور آرنا",materiel:"ابزاردقیق",compan:"E&H -GERMANY"},
{id:"59",idProj:"9",name:" تصفیه خانه آب شهر بم",employer:"شرکت آب منطقه ای کرمان",consultant:"مهندسین مشاور خاک مهار آب",materiel:"میکرو فیلتر )میکرو استرینر)",compan:" TE-GERMANY "},
{id:"60",idProj:"9",name:" تصفیه خانه آب شهر بم",employer:"شرکت آب منطقه ای کرمان",consultant:"مهندسین مشاور خاک مهار آب",materiel:"اشغالگیر مکانیکی ",compan:"KUHN-GERMANY "},
{id:"61",idProj:"9",name:" تصفیه خانه آب شهر بم",employer:"شرکت آب منطقه ای کرمان",consultant:"مهندسین مشاور خاک مهار آب",materiel:" سیستم ضدعفونی توسط هیپوکلریت سدیم ",compan:"SEVERNTRENT  –USA"},
{id:"62",idProj:"9",name:" تصفیه خانه آب شهر بم",employer:"شرکت آب منطقه ای کرمان",consultant:"مهندسین مشاور خاک مهار آب",materiel:"  دستگاه بلت تیکنر ",compan:"ANDRITZ-FRANCE"},
{id:"63",idProj:"9",name:" تصفیه خانه آب شهر بم",employer:"شرکت آب منطقه ای کرمان",consultant:"مهندسین مشاور خاک مهار آب",materiel:" پمپ هلیکال روتور ",compan:"NETZSCH –GERMANY "},
{id:"64",idProj:"9",name:" تصفیه خانه آب شهر بم",employer:"شرکت آب منطقه ای کرمان",consultant:"مهندسین مشاور خاک مهار آب",materiel:"پکیج تزریق مواد شیمیایی ",compan:"MILTONROY-FRANCE, ALLDOS-GERMANY"},
{id:"65",idProj:"9",name:" تصفیه خانه آب شهر بم",employer:"شرکت آب منطقه ای کرمان",consultant:"مهندسین مشاور خاک مهار آب",materiel:"بلوئرهای هوادهی ",compan:"AERZEN-GERMANY"},
{id:"66",idProj:"9",name:" تصفیه خانه آب شهر بم",employer:"شرکت آب منطقه ای کرمان",consultant:"مهندسین مشاور خاک مهار آب",materiel:"تجهیزات کنترل و ابزار دقیق ",compan:"E&H -GERMANY"},
{id:"67",idProj:"3",name:" تصفیه خانه فاضلاب شهر واوان ",employer:"شرکت آب و فاضلاب جنوب غرب استان تهران ",consultant:"شرکت مهندسین مشاور آبران",materiel:"دستگاه بلت تیکنر و بلت فیلتر پرس ",compan:"ANDRITZ-FRANCE"},
{id:"68",idProj:"3",name:" تصفیه خانه فاضلاب شهر واوان ",employer:"شرکت آب و فاضلاب جنوب غرب استان تهران ",consultant:"شرکت مهندسین مشاور آبران",materiel:"الکتروپمپ های مستغرق ",compan:"KSB-GERMANY"},
{id:"69",idProj:"3",name:" تصفیه خانه فاضلاب شهر واوان ",employer:"شرکت آب و فاضلاب جنوب غرب استان تهران ",consultant:"شرکت مهندسین مشاور آبران",materiel:"میکسرهای مستغرق ",compan:"KSB-GERMANY"},
{id:"70",idProj:"3",name:" تصفیه خانه فاضلاب شهر واوان ",employer:"شرکت آب و فاضلاب جنوب غرب استان تهران ",consultant:"شرکت مهندسین مشاور آبران",materiel:"الکتروموتورها ",compan:"SIEMENS-GERMANY"},
{id:"71",idProj:"3",name:" تصفیه خانه فاضلاب شهر واوان ",employer:"شرکت آب و فاضلاب جنوب غرب استان تهران ",consultant:"شرکت مهندسین مشاور آبران",materiel:"دیفیوزرهای هوادهی ",compan:"EDI-USA"},
{id:"72",idProj:"3",name:" تصفیه خانه فاضلاب شهر واوان ",employer:"شرکت آب و فاضلاب جنوب غرب استان تهران ",consultant:"شرکت مهندسین مشاور آبران",materiel:"بلوئرهای هوادهی ",compan:"AERZEN-GERMANY"},
{id:"73",idProj:"3",name:" تصفیه خانه فاضلاب شهر واوان ",employer:"شرکت آب و فاضلاب جنوب غرب استان تهران ",consultant:"شرکت مهندسین مشاور آبران",materiel:"تجهیزات کنترل و ابزار دقیق ",compan:"E&H -GERMANY"},
{id:"74",idProj:"4",name:" تصفیه خانه فاضلاب شهر رودان ",employer:"شرکت آب و فاضلاب استان هرمزگان",consultant:"شرکت مهندسین مشاور پارس آب تدبیر",materiel:"الکتروپمپ های مستغرق ",compan:"KSB-GERMANY"},
{id:"75",idProj:"4",name:" تصفیه خانه فاضلاب شهر رودان ",employer:"شرکت آب و فاضلاب استان هرمزگان",consultant:"شرکت مهندسین مشاور پارس آب تدبیر",materiel:"میکسرهای مستغرق ",compan:"KSB-GERMANY"},
{id:"76",idProj:"4",name:" تصفیه خانه فاضلاب شهر رودان ",employer:"شرکت آب و فاضلاب استان هرمزگان",consultant:"شرکت مهندسین مشاور پارس آب تدبیر",materiel:"الکتروموتور ",compan:"SIEMENS-GERMANY"},
{id:"77",idProj:"4",name:" تصفیه خانه فاضلاب شهر رودان ",employer:"شرکت آب و فاضلاب استان هرمزگان",consultant:"شرکت مهندسین مشاور پارس آب تدبیر",materiel:"جریان ساز ",compan:"GRUNDFOS-DENMARK"},
{id:"78",idProj:"4",name:" تصفیه خانه فاضلاب شهر رودان ",employer:"شرکت آب و فاضلاب استان هرمزگان",consultant:"شرکت مهندسین مشاور پارس آب تدبیر",materiel:"دیفیوزرهای هوادهی ",compan:"EDI-USA"},
{id:"79",idProj:"4",name:" تصفیه خانه فاضلاب شهر رودان ",employer:"شرکت آب و فاضلاب استان هرمزگان",consultant:"شرکت مهندسین مشاور پارس آب تدبیر",materiel:"شیرالات ",compan:"AVK-GERMANY"},
{id:"80",idProj:"4",name:" تصفیه خانه فاضلاب شهر رودان ",employer:"شرکت آب و فاضلاب استان هرمزگان",consultant:"شرکت مهندسین مشاور پارس آب تدبیر",materiel:"بلوئرهای هوادهی ",compan:"AERZEN-GERMANY"},
{id:"81",idProj:"4",name:" تصفیه خانه فاضلاب شهر رودان ",employer:"شرکت آب و فاضلاب استان هرمزگان",consultant:"شرکت مهندسین مشاور پارس آب تدبیر",materiel:"گیربکس ",compan:"NORD-GERMANY"},
{id:"82",idProj:"4",name:" تصفیه خانه فاضلاب شهر رودان ",employer:"شرکت آب و فاضلاب استان هرمزگان",consultant:"شرکت مهندسین مشاور پارس آب تدبیر",materiel:"مرکز دوران پلهای لجن ",compan:"Rothe-Erde –GERMANY"},
{id:"83",idProj:"4",name:" تصفیه خانه فاضلاب شهر رودان ",employer:"شرکت آب و فاضلاب استان هرمزگان",consultant:"شرکت مهندسین مشاور پارس آب تدبیر",materiel:"تجهیزات کنترل و ابزار دقیق ",compan:"E&H -GERMANY"},
{id:"84",idProj:"16",name:" تصفیه خانه فاضلاب دزفول",employer:"شرکت آب و فاضلاب استان خوزستان",consultant:"شرکت مهندسین مشاور ری آب",materiel:"سیستم کلرزنی ",compan:"ALLDOS –GERMANY"},
{id:"85",idProj:"16",name:" تصفیه خانه فاضلاب دزفول",employer:"شرکت آب و فاضلاب استان خوزستان",consultant:"شرکت مهندسین مشاور ری آب",materiel:"تجهیزات کنترل و ابزار دقیق ",compan:"E&H -GERMANY"},
{id:"86",idProj:"16",name:" تصفیه خانه فاضلاب دزفول",employer:"شرکت آب و فاضلاب استان خوزستان",consultant:"شرکت مهندسین مشاور ری آب",materiel:"الکتروموتور ",compan:"SIEMENS-GERMANY"},
{id:"87",idProj:"8",name:" تصفیه خانه آب شهر میانه",employer:"شرکت آب منطقه ای آذربایجان شرقی",consultant:"شرکت مهندسین مشاور آبران",materiel:"پکیج تزریق مواد شیمیایی ",compan:"MILTONROY-FRANCE"},
{id:"88",idProj:"8",name:" تصفیه خانه آب شهر میانه",employer:"شرکت آب منطقه ای آذربایجان شرقی",consultant:"شرکت مهندسین مشاور آبران",materiel:"محرک شیر آلات ",compan:"AUMA"},
{id:"89",idProj:"8",name:" تصفیه خانه آب شهر میانه",employer:"شرکت آب منطقه ای آذربایجان شرقی",consultant:"شرکت مهندسین مشاور آبران",materiel:"سیستم کلرزنی",compan:"ALLDOS –GERMANY"},
{id:"90",idProj:"8",name:" تصفیه خانه آب شهر میانه",employer:"شرکت آب منطقه ای آذربایجان شرقی",consultant:"شرکت مهندسین مشاور آبران",materiel:"بلوئر بکواش فیلتر ",compan:"AERZEN"},
{id:"91",idProj:"8",name:" تصفیه خانه آب شهر میانه",employer:"شرکت آب منطقه ای آذربایجان شرقی",consultant:"شرکت مهندسین مشاور آبران",materiel:"تجهیزات کنترل و ابزار دقیق ",compan:"E&H -GERMANY"},
{id:"92",idProj:"10",name:" تصفیه خانه فاضلاب شهر بهارستان",employer:"شرکت آب و فاضلاب بهارستان اصفهان",consultant:"شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ", materiel:"میکرو فیلتر )میکرو استرینر) ",compan:"TE-GERMANY"},
{id:"93",idProj:"10",name:" تصفیه خانه فاضلاب شهر بهارستان",employer:"شرکت آب و فاضلاب بهارستان اصفهان",consultant:"شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ", materiel:"سیستم ",compan:"UV –OZONIA"},
{id:"94",idProj:"10",name:" تصفیه خانه فاضلاب شهر بهارستان",employer:"شرکت آب و فاضلاب بهارستان اصفهان",consultant:"شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ", materiel:"اسکروپمپ ",compan:"RITZ ATRO-GERMANY"},
{id:"95",idProj:"10",name:" تصفیه خانه فاضلاب شهر بهارستان",employer:"شرکت آب و فاضلاب بهارستان اصفهان",consultant:"شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ", materiel:"دستگاه بلت فیلتر پرس ",compan:"TE-GERMANY"},
{id:"96",idProj:"10",name:" تصفیه خانه فاضلاب شهر بهارستان",employer:"شرکت آب و فاضلاب بهارستان اصفهان",consultant:"شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ", materiel:"دستگاه سانتریفوژ آبگیری لجن ",compan:"HAUS-TURKEY"},
{id:"97",idProj:"10",name:" تصفیه خانه فاضلاب شهر بهارستان",employer:"شرکت آب و فاضلاب بهارستان اصفهان",consultant:"شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ", materiel:"الکتروپمپ های مستغرق ",compan:"KSB-GERMANY"},
{id:"98",idProj:"10",name:" تصفیه خانه فاضلاب شهر بهارستان",employer:"شرکت آب و فاضلاب بهارستان اصفهان",consultant:"شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ", materiel:"میکسر مستغرق ",compan:"KSB-GERMANY"},
{id:"99",idProj:"10",name:" تصفیه خانه فاضلاب شهر بهارستان",employer:"شرکت آب و فاضلاب بهارستان اصفهان",consultant:"شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ", materiel:"پمپ هلیکال روتور ",compan:"NETZSCH –GERMANY"},
{id:"100",idProj:"10",name:" تصفیه خانه فاضلاب شهر بهارستان",employer:"شرکت آب و فاضلاب بهارستان اصفهان",consultant:"شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ", materiel:"الکتروموتور ",compan:"SIEMENS-GERMANY"},
{id:"101",idProj:"10",name:" تصفیه خانه فاضلاب شهر بهارستان",employer:"شرکت آب و فاضلاب بهارستان اصفهان",consultant:"شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ", materiel:"دیفیوزرهای هوادهی ",compan:"EDI-USA"},
{id:"102",idProj:"10",name:" تصفیه خانه فاضلاب شهر بهارستان",employer:"شرکت آب و فاضلاب بهارستان اصفهان",consultant:"شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ", materiel:"بلوئرهای هوادهی ",compan:"AERZEN-GERMANY"},
{id:"103",idProj:"10",name:" تصفیه خانه فاضلاب شهر بهارستان",employer:"شرکت آب و فاضلاب بهارستان اصفهان",consultant:"شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ", materiel:"تجهیزات کنترل و ابزار دقیق ",compan:"E&H -GERMANY"},
{id:"104",idProj:"20",name:" تصفیه خانه آب شهر تکاب",employer:"شرکت سهامی آب منطقه¬ای آذربایجان غربی ",consultant:"شرکت مهندسین مشاور آشناب", materiel:"پکیج تزریق مواد شیمیایی ",compan:"MILTONROY-FRANCE"},
{id:"105",idProj:"20",name:" تصفیه خانه آب شهر تکاب",employer:"شرکت سهامی آب منطقه¬ای آذربایجان غربی ",consultant:"شرکت مهندسین مشاور آشناب", materiel:"وکیوم پمپ پولساتور ",compan:" AERZEN-GERMANY"},
{id:"106",idProj:"20",name:" تصفیه خانه آب شهر تکاب",employer:"شرکت سهامی آب منطقه¬ای آذربایجان غربی ",consultant:"شرکت مهندسین مشاور آشناب", materiel:"سیستم کلرزنی ",compan:"ALLDOS -GERMANY"},
{id:"107",idProj:"20",name:" تصفیه خانه آب شهر تکاب",employer:"شرکت سهامی آب منطقه¬ای آذربایجان غربی ",consultant:"شرکت مهندسین مشاور آشناب", materiel:"میکسرهای شیمیایی",compan:"MILTONROY –FRANCE"}, 
{id:"108",idProj:"20",name:" تصفیه خانه آب شهر تکاب",employer:"شرکت سهامی آب منطقه¬ای آذربایجان غربی ",consultant:"شرکت مهندسین مشاور آشناب", materiel:"بلوئر بکواش فیلتر ",compan:"AERZEN –GERMANY"},
{id:"109",idProj:"20",name:" تصفیه خانه آب شهر تکاب",employer:"شرکت سهامی آب منطقه¬ای آذربایجان غربی ",consultant:"شرکت مهندسین مشاور آشناب", materiel:"Pinch valve",compan:"Miltonroy –France"},
{id:"110",idProj:"18",name:" تصفیه خانه فاضلاب شهر بندر گز",employer:"شرکت آب و فاضلاب گلستان",consultant:"شرکت مهندسین مشاور پژوهاب",materiel:"سیستم کلرزنی ",compan:"JESCO –GERMANY"},
{id:"111",idProj:"18",name:" تصفیه خانه فاضلاب شهر بندر گز",employer:"شرکت آب و فاضلاب گلستان",consultant:"شرکت مهندسین مشاور پژوهاب",materiel:"پمپ های مستغرق ",compan:"FLYGT-SWEDEN"},
{id:"112",idProj:"17",name:" تصفیه خانه فاضلاب شهر کردکوی",employer:"شرکت آب و فاضلاب گلستان",consultant:"شرکت مهندسین مشاور پژوهاب",materiel:"سیستم کلرزنی ",compan:"JESCO –GERMANY"},
{id:"113",idProj:"17",name:" تصفیه خانه فاضلاب شهر کردکوی",employer:"شرکت آب و فاضلاب گلستان",consultant:"شرکت مهندسین مشاور پژوهاب",materiel:"پمپ های مستغرق ",compan:"FLYGT-SWEDEN"},
    

];

export  {ProjSupp}